### ISSUE TITLE
Build 4.2.0 fails

### ISSUE THREAD

**Issue by muka** [warmcat/libwebsockets#2332]
Hi, thank you for the great work :)

I am trying to build as per documentation but cannot get `make` to suceed. I would like to compile with `-DLWS_WITH_EXTERNAL_POLL=ON ` to have it in mosquitto mqtt broker without loss of performance.

I get this warning as error failure. I am sure it's my fault but hopefully a solution can benefit others
Thanks 

```
/build/libwebsockets-4.2.0/lib/core-net/service.c: In function 'lws_service_adjust_timeout':
/build/libwebsockets-4.2.0/lib/core-net/service.c:307:17: error: conversion from 'lws_usec_t' {aka 'long int'} to 'int' may change value [-Werror=conversion]
  307 |    timeout_ms = u / 1000;
      |                 ^
cc1: all warnings being treated as errors
make[2]: *** [lib/CMakeFiles/websockets_shared.dir/build.make:609: lib/CMakeFiles/websockets_shared.dir/core-net/service.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1373: lib/CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by lws-team** [comment]
This is fixed in v4.2-stable branch, use that instead of the initial tag.

**Comment by muka** [comment]
Ok, thank you!

**Comment by muka** [comment]
I have tried with branch 4.2-stable but seems it still persist.

Follow the build excerpt (from dockerfile)
```
ENV LIBWS_VERSION=4.2-stable
RUN wget https://github.com/warmcat/libwebsockets/archive/refs/heads/v${LIBWS_VERSION}.zip && \
    unzip v${LIBWS_VERSION}.zip && cd libwebsockets-${LIBWS_VERSION} && \
    cd libwebsockets-${LIBWS_VERSION} && cmake -DLWS_WITH_EXTERNAL_POLL=ON . && \
    cd libwebsockets-${LIBWS_VERSION} && make && make install
```

The error is the same. Should I use main instead ?

**Comment by lws-team** [comment]
My mistake... I checked against main.  I backported the fix from main to v4.2-stable if you try it again.

**Comment by muka** [comment]
Great, going to try in a moment!

**Comment by muka** [comment]
Retried today but some more warning were showing up related to examples. This worked at the end:
```
cmake -DLWS_WITH_EXTERNAL_POLL=ON -DLWS_WITHOUT_TESTAPPS=ON -DLWS_WITH_MINIMAL_EXAMPLES=OFF . 
```

Thanks!

**Comment by lws-team** [comment]
If you cut and paste the warnings, I will try to do something about them.

Development happens mainly at libwebsockets.org, so I push things there are mirror at github a bit slower.

**Comment by muka** [comment]
This is the command I was using `cmake -DLWS_WITH_EXTERNAL_POLL=ON .`
 
It fails with 
```
[ 97%] Building C object test-apps/CMakeFiles/test-server-extpoll.dir/test-server.c.o
/build/libwebsockets-4.2-stable/test-apps/test-server.c: In function 'lws_callback_http':
/build/libwebsockets-4.2-stable/test-apps/test-server.c:110:17: error: conversion from 'int' to 'short int' may change value [-Werror=conversion]
  110 |   pfd->events = pa->events;
      |                 ^~
/build/libwebsockets-4.2-stable/test-apps/test-server.c:113:19: error: conversion from 'long int' to 'int' may change value [-Werror=conversion]
  113 |   count_pollfds = (pfd - pollfds) + 1;
      |                   ^
/build/libwebsockets-4.2-stable/test-apps/test-server.c:131:17: error: conversion from 'int' to 'short int' may change value [-Werror=conversion]
  131 |   pfd->events = pa->events;
      |                 ^~
/build/libwebsockets-4.2-stable/test-apps/test-server.c: In function 'main':
/build/libwebsockets-4.2-stable/test-apps/test-server.c:573:37: error: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
  573 |  pollfds = malloc(max_poll_elements * sizeof (struct lws_pollfd));
      |                                     ^
/build/libwebsockets-4.2-stable/test-apps/test-server.c:574:39: error: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
  574 |  fd_lookup = malloc(max_poll_elements * sizeof (int));
      |                                       ^
/build/libwebsockets-4.2-stable/test-apps/test-server.c:702:21: error: conversion to 'nfds_t' {aka 'long unsigned int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
  702 |   n = poll(pollfds, count_pollfds, n);
      |                     ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [test-apps/CMakeFiles/test-server-extpoll.dir/build.make:63: test-apps/CMakeFiles/test-server-extpoll.dir/test-server.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1454: test-apps/CMakeFiles/test-server-extpoll.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by lws-team** [comment]
Thanks, I pushed fixes for these on main and v4.2-stable.
