### ISSUE TITLE
ERROR on binding fd xx to port 7861

### ISSUE THREAD

**Issue by 21stcaveman** [warmcat/libwebsockets#2350]
Hi,

I have been using libwebsockets 4.1.0-rc2 on RHEL 8 for a while now with no issues, and decided to upgrade to 4.2.1 today.
Downloaded and built from source, all went well. lwsws was compiled, no issues.
When running it though, I get :
`ERROR on binding fd xx to port 7861 (-1 97)`
`VH test: iface lo port 7861 DOESN'T EXIST`

I have seen different numbers for xx (8, 14, 16).
`netstat -platun` shows port 7861 on lo interface is not taken.
lwsws compiled with 4.1.0-rc2 runs absolutely fine on the same machine, with same configuration.

Has anyone run into this? Any idea why would this happen?

**Comment by lws-team** [comment]
fd xx just means the socketfd, depending on what your app does, it's not strange it might not always be the same each run.

Errno 97 is `EAFNOSUPPORT`, "Address family not supported by protocol".

What does your lwsws vhost conf have in the generic section for "test" vhost?  Is LWS_IPV6 set in the config and ipv6 enabled on the host?

**Comment by 21stcaveman** [comment]
Got it, good to know.
Here is the vhost config :

```
{
        "global": {
                "plugin-dir": "/usr/lib64/lwsws/plugins"
        },
        "vhosts": [{
                "name": "test",
                "port": "7861",
                "interface": "lo",
                "access-log": "/var/log/test/ws-access.log",
                "mounts": [{
                        "mountpoint":"/ws",
                        "origin":"callback://test-protocol"
                }],
                "ws-protocols": [{
                        "test": {
                                "status": "ok",
                                "default": "1"
                        }
                }]
        }]
}
```
and my global config :
```
{
  "global": {
   "uid": "48",
   "gid": "48",
   "interface": "eth0",
   "count-threads": "1",
   "server-string": "lwsws",
   "ws-pingpong-secs": "200",
   "init-ssl": "yes"
 }
}
```

I see no reason for `EAFNOSUPPORT`, do you? A bit strange.

**Comment by lws-team** [comment]
What's the ipv6 situation on the build and on the machine?

**Comment by 21stcaveman** [comment]
ipv6 is enabled on the machine :
```
# sysctl -a 2>/dev/null | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
```

lwsws is built with :
`-DCMAKE_INSTALL_PREFIX:PATH=/usr -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS=1 -DLWS_WITH_DISTRO_RECOMMENDED=1 -DCMAKE_C_FLAGS=-m64`

Not sure if ipv6 is enabled as a result of these flags or not.

**Comment by lws-team** [comment]
Yes `DISTRO_RECOMMENDED` enables it... let me look into it...

**Comment by 21stcaveman** [comment]
Appreciate it.

**Comment by lws-team** [comment]
Does this help?  It should apply on v4.2.1

```
diff --git a/lib/core-net/network.c b/lib/core-net/network.c
index d20a416fdd..f1aac1ac84 100644
--- a/lib/core-net/network.c
+++ b/lib/core-net/network.c
@@ -273,7 +273,8 @@ lws_socket_bind(struct lws_vhost *vhost, struct lws *wsi,
 				return m;
 			}
 			if (serv_addr6.sin6_family == AF_INET6)
-				serv_addr6.sin6_scope_id = (unsigned int)lws_get_addr_scope(iface);
+				serv_addr6.sin6_scope_id = (unsigned int)htonl((uint32_t)
+						lws_get_addr_scope(iface));
 		} else
 			serv_addr6.sin6_family = AF_INET6;
 
diff --git a/lib/plat/unix/unix-sockets.c b/lib/plat/unix/unix-sockets.c
index a2c0e0ac50..218f35d1d2 100644
--- a/lib/plat/unix/unix-sockets.c
+++ b/lib/plat/unix/unix-sockets.c
@@ -277,7 +277,11 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 	struct ifaddrs *ifc;
 #ifdef LWS_WITH_IPV6
 	struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)addr;
+	unsigned long sco = 0, ts;
+	const uint8_t *p;
 #endif
+	int score = 0; /* 0 = no match, 1 = nonnative,
+			  2 = link-local, 3 = global native */
 
 	if (getifaddrs(&ifr)) {
 		lwsl_err("%s: unable to getifaddrs: errno %d\n", __func__, errno);
@@ -306,6 +310,8 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 		case AF_INET:
 #ifdef LWS_WITH_IPV6
 			if (ipv6) {
+				if (score)
+					break;
 				/* map IPv4 to IPv6 */
 				memset((char *)&addr6->sin6_addr, 0,
 						sizeof(struct in6_addr));
@@ -315,16 +321,29 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 				       &((struct sockaddr_in *)ifc->ifa_addr)->sin_addr,
 							sizeof(struct in_addr));
 				lwsl_debug("%s: uplevelling ipv4 bind to ipv6\n", __func__);
-			} else
+				break;
+			}
 #endif
-				memcpy(addr,
-					(struct sockaddr_in *)ifc->ifa_addr,
+			score = 3;
+			memcpy(addr,
+				(struct sockaddr_in *)ifc->ifa_addr,
 						    sizeof(struct sockaddr_in));
 			break;
 #ifdef LWS_WITH_IPV6
 		case AF_INET6:
+			p = (const uint8_t *)
+				&((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr;
+			ts = 2;
+			if (p[0] == 0xff && (p[1] & 0xf) == 0xe)
+				ts = 3;
+
+			if (sco >= ts)
+				break;
+
+			sco = ts;
+
 			memcpy(&addr6->sin6_addr,
-			  &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
+			     &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
 						       sizeof(struct in6_addr));
 			break;
 #endif
```

**Comment by 21stcaveman** [comment]
Unfortunately, it does not.
However, I found out that this has to do with the `lo` interface.
if I comment out `"interface": "lo",` line in the vhost config posted above, lwsws 4.2.1 runs just fine, listening to port 7861 on ipv6 :::7861

same line works for lwsws v4.1.0-rc2, resulting in it listening on ipv4 127.0.01:7861
Hope that helps.

**Comment by lws-team** [comment]
Then how about this

```
diff --git a/lib/core-net/network.c b/lib/core-net/network.c
index d20a416fdd..f1aac1ac84 100644
--- a/lib/core-net/network.c
+++ b/lib/core-net/network.c
@@ -273,7 +273,8 @@ lws_socket_bind(struct lws_vhost *vhost, struct lws *wsi,
 				return m;
 			}
 			if (serv_addr6.sin6_family == AF_INET6)
-				serv_addr6.sin6_scope_id = (unsigned int)lws_get_addr_scope(iface);
+				serv_addr6.sin6_scope_id = (unsigned int)htonl((uint32_t)
+						lws_get_addr_scope(iface));
 		} else
 			serv_addr6.sin6_family = AF_INET6;
 
diff --git a/lib/plat/unix/unix-sockets.c b/lib/plat/unix/unix-sockets.c
index a2c0e0ac50..5f5a8d97f2 100644
--- a/lib/plat/unix/unix-sockets.c
+++ b/lib/plat/unix/unix-sockets.c
@@ -277,7 +277,11 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 	struct ifaddrs *ifc;
 #ifdef LWS_WITH_IPV6
 	struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)addr;
+	unsigned long sco = 0, ts;
+	const uint8_t *p;
 #endif
+	int score = 0; /* 0 = no match, 1 = nonnative,
+			  2 = link-local, 3 = global native */
 
 	if (getifaddrs(&ifr)) {
 		lwsl_err("%s: unable to getifaddrs: errno %d\n", __func__, errno);
@@ -299,13 +303,18 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 #if defined(AF_PACKET)
 		case AF_PACKET:
 			/* interface exists but is not usable */
-			rc = LWS_ITOSA_NOT_USABLE;
+			if (rc == LWS_ITOSA_NOT_EXIST)
+				rc = LWS_ITOSA_NOT_USABLE;
 			continue;
 #endif
 
 		case AF_INET:
 #ifdef LWS_WITH_IPV6
 			if (ipv6) {
+				if (score)
+					break;
+				sco = 1;
+				rc = LWS_ITOSA_USABLE;
 				/* map IPv4 to IPv6 */
 				memset((char *)&addr6->sin6_addr, 0,
 						sizeof(struct in6_addr));
@@ -315,23 +324,37 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 				       &((struct sockaddr_in *)ifc->ifa_addr)->sin_addr,
 							sizeof(struct in_addr));
 				lwsl_debug("%s: uplevelling ipv4 bind to ipv6\n", __func__);
-			} else
+				break;
+			}
 #endif
-				memcpy(addr,
-					(struct sockaddr_in *)ifc->ifa_addr,
+			sco = 3;
+			rc = LWS_ITOSA_USABLE;
+			memcpy(addr,
+				(struct sockaddr_in *)ifc->ifa_addr,
 						    sizeof(struct sockaddr_in));
 			break;
 #ifdef LWS_WITH_IPV6
 		case AF_INET6:
+			p = (const uint8_t *)
+				&((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr;
+			ts = 2;
+			if (p[0] == 0xff && (p[1] & 0xf) == 0xe)
+				ts = 3;
+
+			if (sco >= ts)
+				break;
+
+			sco = ts;
+			rc = LWS_ITOSA_USABLE;
+
 			memcpy(&addr6->sin6_addr,
-			  &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
+			     &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
 						       sizeof(struct in6_addr));
 			break;
 #endif
 		default:
 			continue;
 		}
-		rc = LWS_ITOSA_USABLE;
 	}
 
 	freeifaddrs(ifr);
```

**Comment by 21stcaveman** [comment]
same result. As soon as I uncomment loopback interface in the config, I get :

```
lwsws libwebsockets web server - license CC0 + MIT
(C) Copyright 2010-2020 Andy Green <andy@warmcat.com>
Using config dir: "/etc/lwsws"
LWS: 4.2.1-v4.2.1, loglevel 1031
NET CLI SRV H1 H2 WS MQTT SS-JSON-POL SSPROX ConMon IPV6-on
   /usr/lib64/libwebsockets-evlib_uv.so
Scandir on '/usr/share/libwebsockets-test-server/plugins/' failed, errno 2
 Using foreign event loop...
 ++ [4000|wsi|0|pipe] (1)
 ++ [4000|vh|0|netlink] (1)
 ++ [4000|vh|1|test|lo|lo|7861] (2)
 Vhost 'test' using non-TLS mode
ERROR on binding fd 14 to port 7861 (-1 97)
VH test: iface lo port 7861 DOESN'T EXIST
lws_plat_drop_app_privileges: effective group 'apache'
lws_plat_drop_app_privileges: effective user 'apache'
```

here is the ifconfig :
```
# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.31.28.104  netmask 255.255.240.0  broadcast 172.31.31.255
        inet6 fe80::b:18ff:fe91:711b  prefixlen 64  scopeid 0x20<link>
        ether 02:0b:18:91:71:1b  txqueuelen 1000  (Ethernet)
        RX packets 66777  bytes 74808332 (71.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26550  bytes 3794444 (3.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 103  bytes 10630 (10.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 103  bytes 10630 (10.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by lws-team** [comment]
OK... sorry this has been a bit iterative.  I think I get all the angles now, please try this

```
diff --git a/lib/core-net/network.c b/lib/core-net/network.c
index d20a416fdd..f1aac1ac84 100644
--- a/lib/core-net/network.c
+++ b/lib/core-net/network.c
@@ -273,7 +273,8 @@ lws_socket_bind(struct lws_vhost *vhost, struct lws *wsi,
 				return m;
 			}
 			if (serv_addr6.sin6_family == AF_INET6)
-				serv_addr6.sin6_scope_id = (unsigned int)lws_get_addr_scope(iface);
+				serv_addr6.sin6_scope_id = (unsigned int)htonl((uint32_t)
+						lws_get_addr_scope(iface));
 		} else
 			serv_addr6.sin6_family = AF_INET6;
 
diff --git a/lib/plat/unix/unix-sockets.c b/lib/plat/unix/unix-sockets.c
index a2c0e0ac50..5f5a8d97f2 100644
--- a/lib/plat/unix/unix-sockets.c
+++ b/lib/plat/unix/unix-sockets.c
@@ -277,7 +277,11 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 	struct ifaddrs *ifc;
 #ifdef LWS_WITH_IPV6
 	struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)addr;
+	unsigned long sco = 0, ts;
+	const uint8_t *p;
 #endif
+	int score = 0; /* 0 = no match, 1 = nonnative,
+			  2 = link-local, 3 = global native */
 
 	if (getifaddrs(&ifr)) {
 		lwsl_err("%s: unable to getifaddrs: errno %d\n", __func__, errno);
@@ -299,13 +303,18 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 #if defined(AF_PACKET)
 		case AF_PACKET:
 			/* interface exists but is not usable */
-			rc = LWS_ITOSA_NOT_USABLE;
+			if (rc == LWS_ITOSA_NOT_EXIST)
+				rc = LWS_ITOSA_NOT_USABLE;
 			continue;
 #endif
 
 		case AF_INET:
 #ifdef LWS_WITH_IPV6
 			if (ipv6) {
+				if (score)
+					break;
+				sco = 1;
+				rc = LWS_ITOSA_USABLE;
 				/* map IPv4 to IPv6 */
 				memset((char *)&addr6->sin6_addr, 0,
 						sizeof(struct in6_addr));
@@ -315,23 +324,37 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 				       &((struct sockaddr_in *)ifc->ifa_addr)->sin_addr,
 							sizeof(struct in_addr));
 				lwsl_debug("%s: uplevelling ipv4 bind to ipv6\n", __func__);
-			} else
+				break;
+			}
 #endif
-				memcpy(addr,
-					(struct sockaddr_in *)ifc->ifa_addr,
+			sco = 3;
+			rc = LWS_ITOSA_USABLE;
+			memcpy(addr,
+				(struct sockaddr_in *)ifc->ifa_addr,
 						    sizeof(struct sockaddr_in));
 			break;
 #ifdef LWS_WITH_IPV6
 		case AF_INET6:
+			p = (const uint8_t *)
+				&((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr;
+			ts = 2;
+			if (p[0] == 0xff && (p[1] & 0xf) == 0xe)
+				ts = 3;
+
+			if (sco >= ts)
+				break;
+
+			sco = ts;
+			rc = LWS_ITOSA_USABLE;
+
 			memcpy(&addr6->sin6_addr,
-			  &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
+			     &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
 						       sizeof(struct in6_addr));
 			break;
 #endif
 		default:
 			continue;
 		}
-		rc = LWS_ITOSA_USABLE;
 	}
 
 	freeifaddrs(ifr);
```

**Comment by 21stcaveman** [comment]
no worries at all, appreciate the fast turn around actually!

I'm getting a conversion error with the last patch :
```
/usr/src/libwebsockets/BUILD/lib/plat/unix/unix-sockets.c:349:10: error: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
     ts = IP_SCORE_IPV6_SCOPE_BASE + (p[1] & 0xf);
          ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by lws-team** [comment]
It just needs to be

```ts = (unsigned long)(IP_SCORE_IPV6_SCOPE_BASE + (p[1] & 0xf));```

**Comment by 21stcaveman** [comment]
sadly, same result.

**Comment by lws-team** [comment]
Ugh, left something dumb in... from the patch, just change

```
for (ifc = ifr; ifc != NULL && rc; ifc = ifc->ifa_next) {
```

to

```
for (ifc = ifr; ifc != NULL; ifc = ifc->ifa_next) {
```

**Comment by 21stcaveman** [comment]
hmm.. couldn't find it in the patch. I made that change, but get the same result unfortunately. Here is the patch I applied:

```
diff --git a/lib/core-net/network.c b/lib/core-net/network.c
index d20a416f..f1aac1ac 100644
--- a/lib/core-net/network.c
+++ b/lib/core-net/network.c
@@ -273,7 +273,8 @@ lws_socket_bind(struct lws_vhost *vhost, struct lws *wsi,
                                return m;
                        }
                        if (serv_addr6.sin6_family == AF_INET6)
-                               serv_addr6.sin6_scope_id = (unsigned int)lws_get_addr_scope(iface);
+                               serv_addr6.sin6_scope_id = (unsigned int)htonl((uint32_t)
+                                               lws_get_addr_scope(iface));
                } else
                        serv_addr6.sin6_family = AF_INET6;

diff --git a/lib/plat/unix/unix-sockets.c b/lib/plat/unix/unix-sockets.c
index a2c0e0ac..2b99dd3d 100644
--- a/lib/plat/unix/unix-sockets.c
+++ b/lib/plat/unix/unix-sockets.c
@@ -267,6 +267,14 @@ lws_plat_set_socket_options_ip(lws_sockfd_type fd, uint8_t pri, int lws_flags)

 /* cast a struct sockaddr_in6 * into addr for ipv6 */

+enum {
+       IP_SCORE_NONE,
+       IP_SCORE_NONNATIVE,
+       IP_SCORE_IPV6_SCOPE_BASE,
+       /* ipv6 scopes */
+       IP_SCORE_GLOBAL_NATIVE = 18
+};
+
 int
 lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
                    size_t addrlen)
@@ -277,14 +285,17 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
        struct ifaddrs *ifc;
 #ifdef LWS_WITH_IPV6
        struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)addr;
+       unsigned long ts;
+       const uint8_t *p;
 #endif
+       unsigned long sco = IP_SCORE_NONE;

        if (getifaddrs(&ifr)) {
                lwsl_err("%s: unable to getifaddrs: errno %d\n", __func__, errno);

                return LWS_ITOSA_USABLE;
        }
-       for (ifc = ifr; ifc != NULL && rc; ifc = ifc->ifa_next) {
+       for (ifc = ifr; ifc != NULL; ifc = ifc->ifa_next) {
                if (!ifc->ifa_addr || !ifc->ifa_name)
                        continue;

@@ -299,13 +310,19 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 #if defined(AF_PACKET)
                case AF_PACKET:
                        /* interface exists but is not usable */
-                       rc = LWS_ITOSA_NOT_USABLE;
+                       if (rc == LWS_ITOSA_NOT_EXIST)
+                               rc = LWS_ITOSA_NOT_USABLE;
                        continue;
 #endif

                case AF_INET:
 #ifdef LWS_WITH_IPV6
                        if (ipv6) {
+                               /* any existing solution is better than this */
+                               if (sco != IP_SCORE_NONE)
+                                       break;
+                               sco = IP_SCORE_NONNATIVE;
+                               rc = LWS_ITOSA_USABLE;
                                /* map IPv4 to IPv6 */
                                memset((char *)&addr6->sin6_addr, 0,
                                                sizeof(struct in6_addr));
@@ -315,23 +332,36 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
                                       &((struct sockaddr_in *)ifc->ifa_addr)->sin_addr,
                                                        sizeof(struct in_addr));
                                lwsl_debug("%s: uplevelling ipv4 bind to ipv6\n", __func__);
-                       } else
+                               break;
+                       }
 #endif
-                               memcpy(addr,
-                                       (struct sockaddr_in *)ifc->ifa_addr,
+                       sco = IP_SCORE_GLOBAL_NATIVE;
+                       rc = LWS_ITOSA_USABLE;
+                       memcpy(addr, (struct sockaddr_in *)ifc->ifa_addr,
                                                    sizeof(struct sockaddr_in));
                        break;
 #ifdef LWS_WITH_IPV6
                case AF_INET6:
+                       p = (const uint8_t *)
+                               &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr;
+                       ts = IP_SCORE_IPV6_SCOPE_BASE;
+                       if (p[0] == 0xff)
+                               ts = (unsigned long)(IP_SCORE_IPV6_SCOPE_BASE + (p[1] & 0xf));
+
+                       if (sco >= ts)
+                               break;
+
+                       sco = ts;
+                       rc = LWS_ITOSA_USABLE;
+
                        memcpy(&addr6->sin6_addr,
-                         &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
+                            &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
                                                       sizeof(struct in6_addr));
                        break;
 #endif
                default:
                        continue;
                }
-               rc = LWS_ITOSA_USABLE;
        }

        freeifaddrs(ifr);
@@ -343,7 +373,6 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
        return rc;
 }

-
 const char *
 lws_plat_inet_ntop(int af, const void *src, char *dst, socklen_t cnt)
 {
```

**Comment by lws-team** [comment]
I pushed what I have on v4.2-stable, I checked using `"interface": "lo"` here and it works without problems for me since the last patch I pasted here.

https://libwebsockets.org/git/libwebsockets/commit?id=6435bfe3097a5ba6dcb68efe616177e29f913f07

**Comment by 21stcaveman** [comment]
Sorry, fell asleep on the keyboard! Interesting. I pulled 4.2-stable, and I still get the same result :
```
lwsws libwebsockets web server - license CC0 + MIT
(C) Copyright 2010-2020 Andy Green <andy@warmcat.com>
Using config dir: "/etc/lwsws"
LWS: 4.2.1-v4.2.1-4-g1f99c206, loglevel 1031
NET CLI SRV H1 H2 WS MQTT SS-JSON-POL SSPROX ConMon IPV6-on
   /usr/lib64/libwebsockets-evlib_uv.so
Scandir on '/usr/share/libwebsockets-test-server/plugins/' failed, errno 2
 Using foreign event loop...
 ++ [7391|wsi|0|pipe] (1)
 ++ [7391|vh|0|netlink] (1)
 ++ [7391|vh|1|test|lo|lo|7861] (2)
 Vhost 'test' using non-TLS mode
ERROR on binding fd 14 to port 7861 (-1 97)
VH test: iface lo port 7861 DOESN'T EXIST
lws_plat_drop_app_privileges: effective group 'apache'
lws_plat_drop_app_privileges: effective user 'apache'
```
Curious about this line : `[7391|vh|1|test|lo|lo|7861]`
Why is `lo` mentioned twice?

Do you mind sharing your vhost config? Want to make sure I'm not missing anything there...

**Comment by lws-team** [comment]
I tested main branch with the patch on a config based on the libwebsockets.org one that I use to test lwsws in parallel with the main service, it's has the same things in it as the main one but different ports so I can run alongside the real one.

The relevant part of that is 

```
{
 "vhosts": [ {
     "name": "libwebsockets.org",
     "port": "1443",
     "host-ssl-key":  "/etc/letsencrypt/live/libwebsockets.org/privkey.pem",
     "host-ssl-cert": "/etc/letsencrypt/live/libwebsockets.org/fullchain.pem",
     "access-log": "/var/log/lwsws/lws-access-log",
     "error-document-404": "/404.html",
     "disable-no-protocol-ws-upgrades": "on",
     "sts": "on",
     "enable-client-ssl": "on",
     "listen-accept-role": "raw-proxy",
     "listen-accept-protocol": "raw-proxy",
     "fallback-listen-accept": "1",
     "allow-non-tls": "1",
        "interface":    "lo",

     "mounts": [{
...
```

that gets me

```
[2021/07/21 06:35:26:7330] N:  ++ [vh|1|libwebsockets.org|lo|lo|1443] (2)
[2021/07/21 06:35:26:7331] N: [vh|1|libwebsockets.org|lo|lo|1443]: lws_create_vhost:    STS enabled
[2021/07/21 06:35:26:7331] N:  SSL ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!HMAC_SHA1:!SHA1:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES128-SHA256:!AES128-GCM-SHA256:!AES128-SHA256:!DHE-RSA-AES256-SHA256:!AES256-GCM-SHA384:!AES256-SHA256'
[2021/07/21 06:35:26:7331] N:  Vhost 'libwebsockets.org' using TLS mode
[2021/07/21 06:35:26:7469] N: lws_interface_to_sa: sco 18
[2021/07/21 06:35:26:7472] N: lws_interface_to_sa: sco 18
[2021/07/21 06:35:26:7472] N: [null wsi]: lws_socket_bind: source ads 127.0.0.1
[2021/07/21 06:35:26:7472] N:  ++ [wsi|1|listen|libwebsockets.org|lo|1443] (2)
[2021/07/21 06:35:26:7474] N: lws_interface_to_sa: sco 2
[2021/07/21 06:35:26:7476] N: lws_interface_to_sa: sco 2
[2021/07/21 06:35:26:7476] N: [null wsi]: lws_socket_bind: source ads ::1
[2021/07/21 06:35:26:7477] N:  ++ [wsi|2|listen|libwebsockets.org|lo|1443] (3)
```

lo is

```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 13870256  bytes 2815820418 (2.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13870256  bytes 2815820418 (2.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

It's possible main and v4.2-stable act slightly differently, on main there are changes to how listen sockets work... previously we open one listen socket and expect the OS to route ipv4 and ipv6 connections there, on main it explicitly opens separate sockets for one vhost that wants to listen on AF_INET and AF_INET6 and handles connections from both sockets at the same vhost.

**Comment by 21stcaveman** [comment]
hmm.. built main with this patch :
```
diff --git a/lib/core-net/network.c b/lib/core-net/network.c
index 77c7752c..2af2d03d 100644
--- a/lib/core-net/network.c
+++ b/lib/core-net/network.c
@@ -274,8 +274,8 @@ lws_socket_bind(struct lws_vhost *vhost, struct lws *wsi,
                                return m;
                        }
                        if (serv_addr6.sin6_family == AF_INET6)
-                               serv_addr6.sin6_scope_id = (unsigned int)
-                                       lws_get_addr_scope(wsi, iface);
+                               serv_addr6.sin6_scope_id = (unsigned int)htonl((uint32_t)
+                                       lws_get_addr_scope(wsi, iface));
                } else
                        serv_addr6.sin6_family = AF_INET6;

diff --git a/lib/plat/unix/unix-sockets.c b/lib/plat/unix/unix-sockets.c
index 525fcfc5..dd844090 100644
--- a/lib/plat/unix/unix-sockets.c
+++ b/lib/plat/unix/unix-sockets.c
@@ -277,6 +277,14 @@ lws_plat_set_socket_options_ip(lws_sockfd_type fd, uint8_t pri, int lws_flags)

 /* cast a struct sockaddr_in6 * into addr for ipv6 */

+enum {
+       IP_SCORE_NONE,
+       IP_SCORE_NONNATIVE,
+       IP_SCORE_IPV6_SCOPE_BASE,
+       /* ipv6 scopes */
+       IP_SCORE_GLOBAL_NATIVE = 18
+};
+
 int
 lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
                    size_t addrlen)
@@ -287,6 +295,9 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
        struct ifaddrs *ifc;
 #ifdef LWS_WITH_IPV6
        struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)addr;
+       unsigned long sco = IP_SCORE_NONE;
+       unsigned long ts;
+       const uint8_t *p;
 #endif

        if (getifaddrs(&ifr)) {
@@ -294,7 +305,7 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,

                return LWS_ITOSA_USABLE;
        }
-       for (ifc = ifr; ifc != NULL && rc; ifc = ifc->ifa_next) {
+       for (ifc = ifr; ifc != NULL; ifc = ifc->ifa_next) {
                if (!ifc->ifa_addr || !ifc->ifa_name)
                        continue;

@@ -309,13 +320,19 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
 #if defined(AF_PACKET)
                case AF_PACKET:
                        /* interface exists but is not usable */
-                       rc = LWS_ITOSA_NOT_USABLE;
+                       if (rc == LWS_ITOSA_NOT_EXIST)
+                               rc = LWS_ITOSA_NOT_USABLE;
                        continue;
 #endif

                case AF_INET:
-#ifdef LWS_WITH_IPV6
+#if defined(LWS_WITH_IPV6)
                        if (ipv6) {
+                               /* any existing solution is better than this */
+                               if (sco != IP_SCORE_NONE)
+                                       break;
+                               sco = IP_SCORE_NONNATIVE;
+                               rc = LWS_ITOSA_USABLE;
                                /* map IPv4 to IPv6 */
                                memset((char *)&addr6->sin6_addr, 0,
                                                sizeof(struct in6_addr));
@@ -325,14 +342,29 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
                                       &((struct sockaddr_in *)ifc->ifa_addr)->sin_addr,
                                                        sizeof(struct in_addr));
                                lwsl_debug("%s: uplevelling ipv4 bind to ipv6\n", __func__);
-                       } else
+                               break;
+                       }
+
+                       sco = IP_SCORE_GLOBAL_NATIVE;
 #endif
-                               memcpy(addr,
-                                       (struct sockaddr_in *)ifc->ifa_addr,
+                       rc = LWS_ITOSA_USABLE;
+                       memcpy(addr, (struct sockaddr_in *)ifc->ifa_addr,
                                                    sizeof(struct sockaddr_in));
                        break;
-#ifdef LWS_WITH_IPV6
+#if defined(LWS_WITH_IPV6)
                case AF_INET6:
+                       p = (const uint8_t *)
+                               &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr;
+                       ts = IP_SCORE_IPV6_SCOPE_BASE;
+                       if (p[0] == 0xff)
+                               ts = (unsigned long)(IP_SCORE_IPV6_SCOPE_BASE + (p[1] & 0xf));
+
+                       if (sco >= ts)
+                               break;
+
+                       sco = ts;
+                       rc = LWS_ITOSA_USABLE;
+
                        memcpy(&addr6->sin6_addr,
                          &((struct sockaddr_in6 *)ifc->ifa_addr)->sin6_addr,
                                                       sizeof(struct in6_addr));
@@ -341,7 +373,6 @@ lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
                default:
                        continue;
                }
-               rc = LWS_ITOSA_USABLE;
        }

        freeifaddrs(ifr);
```

now when I run lwsws, I get this on a never ending loop!!
`[2021/07/20 23:40:33:7343] E: [null wsi]: lws_socket_bind: ERROR on binding fd 18 to port 7861 (-1 97)`

Not sure why you can run it fine and it breaks on mine! strange. Any particular library versions you would like me to check?

**Comment by lws-team** [comment]
The exact patch on main I am using is here

https://libwebsockets.org/git/libwebsockets/commit?id=5ddb03d14674a81860f3b18ba74c2f17a30d4942

You can get the whole tree from _temp branch at git fetch https://libwebsockets.org/repo/libwebsockets +_temp:_temp

It looks like what happens on your box is for ipv6, it thinks the best it can do is try to bind to ::ffff:127.0.0.1 for ipv6, and the OS rejects it.

It does that in case you asked for an ipv6 address for the interface, but it only has an ipv4 one. 

https://libwebsockets.org/git/libwebsockets/commit?id=5ddb03d14674a81860f3b18ba74c2f17a30d4942

These results are "scored", that kind of result is the lowest score.  If it sees a native ipv6 address, if will prefer that, and if it sees multiple sorts of address, it will prefer the one with the widest scope, ie, a global address rather than a link-local one etc.  For lo here, it ends up with host-local ::1 as the answer.

Maybe with this in mind you can use lws_notice() or something in the loop and find out what actually happens in your case.

**Comment by 21stcaveman** [comment]
Well, turns out this patch works perfectly fine on top of main :
https://libwebsockets.org/git/libwebsockets/commit?id=5ddb03d14674a81860f3b18ba74c2f17a30d4942

Applied it, and now lwsws runs fine, listening to 7861 on both 127.0.0.1 and ::1
Guess I missed a line or two in my previous patch!!

Thank you for fast responses and quick turn around Andy, much appreciated.

**Comment by lws-team** [comment]
Great, thanks for the help trying the patches.
