### ISSUE TITLE
libwebsocket 4.3.2 is asking for zlib when compiling on windows

### ISSUE THREAD

**Issue by sushant126** [warmcat/libwebsockets#2688]
I have tryied below command to compile libwebsocket on windows :

**cmake -G "NMake Makefiles" -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DCMAKE_BUILD_TYPE=RELEASE -DOPENSSL_ROOT_DIR="C:\\Program Files\\OpenSSL-Win64" -DCMAKE_INSTALL_PREFIX="C:\\Program Files\\libwebsockets" ..**

Error message:
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:892 (find_package)

So how to solve this isuue , because we dont want install explicitly zlib .
so is there Flag while building cmake so that zlib dependency can handel by libwebsocket ?

**Comment by lws-team** [comment]
Yeah but by default, it uses an internal zlib implementation if it's win32 platform

```
set(LWS_WITH_BUNDLED_ZLIB_DEFAULT OFF)
if(WIN32)
        set(LWS_WITH_BUNDLED_ZLIB_DEFAULT ON)
endif()
```
You might want to delete your CMakeCache.txt if it's saying something different.

**Comment by sushant126** [comment]
I am running command on X64 Native command prompt :
 I have deleted CMakeCache.txt but still same errror :
 below options i have passed to cmake:
 cmake -G "NMake Makefiles" -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DCMAKE_BUILD_TYPE=RELEASE -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" -DCMAKE_INSTALL_PREFIX="C:\Program Files\libwebsockets" **-DLWS_WITH_BUNDLED_ZLIB_DEFAULT= ON** ..
 
 like this do we need to set if i dont have zlib on my machine ?

**Comment by lws-team** [comment]
Where did the lws come from and what version is it?

You don't have to explicitly set that option.  Lws will set it by default, that's why your problem is surprising.

For reference, here's main branch from a few days ago built for 64-bit windows

https://libwebsockets.org/sai/index.html?task=5c71002e7d34d51de68e09334951188de1266b3638c6f67a92486ff084697f66

**Comment by sushant126** [comment]
i am using  git clone --single-branch https://github.com/warmcat/libwebsockets -b v4.3-stable

i have check link shared by you in that libwebsocket build command is:
**cmake .. -DLWS_OPENSSL_LIBRARIES="C:\Program Files\OpenSSL\lib\libssl.lib;C:\Program Files\OpenSSL\lib\libcrypto.lib" -DLWS_OPENSSL_INCLUDE_DIRS="C:\Program Files\OpenSSL\include"**
 Which works fine on my machine but if i add below options it is asking for zlib .
 **-DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1**
 cmake command :
  cmake .. -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DLWS_OPENSSL_LIBRARIES="C:\Program Files\OpenSSL\lib\libssl.lib;C:\Program Files\OpenSSL\lib\libcrypto.lib" -DLWS_OPENSSL_INCLUDE_DIRS="C:\Program Files\OpenSSL\include"

so in your setup -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 this options are not set

**Comment by lws-team** [comment]
`DLWS_SSL_SERVER_WITH_ECDH_CERT` doesn't do anything useful any more AFAIK.

If you want permessage-deflate, yes it must have zlib, but the internal one should do.  Does this help?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 166d48a456..af1b1e6e1d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -882,7 +882,7 @@ endif()
 #
 # ZLIB (needed for deflate extension and if LWS_WITH_HTTP_STREAM_COMPRESSION)
 #
-if (LWS_WITH_ZLIB)
+if (LWS_WITH_ZLIB AND NOT LWS_WITH_BUNDLED_ZLIB)
        if (NOT ZLIB_FOUND)
                if (LWS_WITH_MINIZ)
                        find_package(Miniz REQUIRED)
```

**Comment by sushant126** [comment]
I have tried with above changes  ,It is asking for zlib cmake error:
CMake Error at D:/software/cmake-3.15.3-win64-x64/share/cmake-**3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  D:/software/cmake-3.15.3-win64-x64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  D:/software/cmake-3.15.3-win64-x64/share/cmake-3.15/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:892 (find_package)**
  
so if i want permessage-deflate ,do we need to compile and install zlib for X64   ?

**Comment by lws-team** [comment]
What is `LWS_WITH_BUNDLED_ZLIB` in your CMakeCache?  It should be set to 1

> so if i want permessage-deflate ,do i need to compile and install zlib for X64 ?

One way or another, yes.  But it's supposed to be built with lws on win32.

**Comment by sushant126** [comment]
Sorry it was my mistake when i add below lines in cmakelist.txt
if (LWS_WITH_ZLIB AND NOT LWS_WITH_BUNDLED_ZLIB)
        if (NOT ZLIB_FOUND)
                if (LWS_WITH_MINIZ)
                        find_package(Miniz REQUIRED)
                        
In this case i am getting compilation error , not cmake zlib error.
**libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.h(28): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\cl.exe' : return code '0x2'**                        

I need to compile Libwebsocket for X64 only. so which approach do i need to select now ?

**Comment by lws-team** [comment]
Does this help?

```
diff --git a/lib/plat/windows/CMakeLists.txt b/lib/plat/windows/CMakeLists.txt
index c26c8e7714..12319ae3a7 100644
--- a/lib/plat/windows/CMakeLists.txt
+++ b/lib/plat/windows/CMakeLists.txt
@@ -82,7 +82,7 @@ endif()
 set(WIN32_HELPERS_PATH ../win32port/win32helpers)
 
 # from our perspective in ./lib/plat/windows
-include_directories(../../${WIN32_HELPERS_PATH})
+include_directories(../../${WIN32_HELPERS_PATH} ../../${WIN32_HELPERS_PATH}/zip)
 
 list(APPEND SOURCES
        ${WIN32_HELPERS_PATH}/gettimeofday.c
```

**Comment by sush126** [comment]
I have deleted CMAKEcache and rebuild it ,but still same error:
**libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.h(28): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\cl.exe' : return code '0x2'**

**Comment by lws-team** [comment]
Sorry the patch above should have zlib on the end as shown now.

Assuming you applied the above patch and then did that, then you need to check what include paths the compiler is using.  On Linux you can do `make VERBOSE=1` to see the compiler commandlines, dunno what you should do on Windows.  It should have something like `-Iwin32port/win32helpers/zlib`.

**Comment by lws-team** [comment]
This is solved by the patch or still problems?

**Comment by sush126** [comment]
No it is not solved error unable to find zlib.h

cl   -DLWS_BUILDING_STATIC -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -ID:\test_lib\libweb4.3\libwebsockets\include -ID:\test_lib\libweb4.3\libwebsockets\build -ID:\test_lib\libweb4.3\libwebsockets\lib -ID:\test_lib\libweb4.3\libwebsockets\lib\. -ID:\test_lib\libweb4.3\libwebsockets\lib\plat\windows\. -ID:\test_lib\libweb4.3\libwebsockets\lib\plat\windows\..\..\..\win32port\win32helpers -ID:\test_lib\libweb4.3\libwebsockets\lib\plat\windows\..\..\..\win32port\win32helpers\zlib -ID:\test_lib\libweb4.3\libwebsockets\lib\tls\. -ID:\test_lib\libweb4.3\libwebsockets\lib\core\. -ID:\test_lib\libweb4.3\libwebsockets\lib\misc\. -ID:\test_lib\libweb4.3\libwebsockets\lib\system\.\async-dns -ID:\test_lib\libweb4.3\libwebsockets\lib\system\metrics\. -ID:\test_lib\libweb4.3\libwebsockets\lib\core-net\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\http\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\http\.\compression -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\h1\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\h2\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\raw-skt\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\raw-file\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\listen\. -ID:\test_lib\libweb4.3\libwebsockets\lib\event-libs\. -ID:\test_lib\libweb4.3\libwebsockets\lib\event-libs\poll\..\poll -IC:\PROGRA~1\OPENSS~1\include  /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /DNDEBUG   /W3 /WX /Zc:preprocessor /wd5105 /FoCMakeFiles\websockets.dir\roles\ws\ext\extension.c.obj /FdCMakeFiles\websockets.dir\websockets.pdb /FS -c D:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\ext\extension.c

extension.c
D:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.h(28): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by sush126** [comment]
nope , in as i see  zlib is present in below path:
D:\test_lib\libweb4.3\libwebsockets\win32port\zlib

**Comment by lws-team** [comment]
You'll need to adjust the patch I pasted here in the 10th comment to make that path correct.  And please let me know what the working version of the patch looks like.

**Comment by sush126** [comment]
Hi Andy , 
 I have modify path now it is taking correct zlib path from your project , but still facing compilation error:
 
 cl   -DLWS_BUILDING_STATIC -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -ID:\test_lib\libweb4.3\libwebsockets\include -ID:\test_lib\libweb4.3\libwebsockets\buildwin -ID:\test_lib\libweb4.3\libwebsockets\lib -ID:\test_lib\libweb4.3\libwebsockets\lib\. -ID:\test_lib\libweb4.3\libwebsockets\lib\plat\windows\. -ID:\test_lib\libweb4.3\libwebsockets\lib\plat\windows\..\..\..\win32port\win32helpers -**ID:\test_lib\libweb4.3\libwebsockets\lib\plat\windows\..\..\..\win32port\zlib -**ID:\test_lib\libweb4.3\libwebsockets\lib\tls\. -ID:\test_lib\libweb4.3\libwebsockets\lib\core\. -ID:\test_lib\libweb4.3\libwebsockets\lib\misc\. -ID:\test_lib\libweb4.3\libwebsockets\lib\system\.\async-dns -ID:\test_lib\libweb4.3\libwebsockets\lib\system\metrics\. -ID:\test_lib\libweb4.3\libwebsockets\lib\core-net\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\http\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\http\.\compression -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\h1\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\h2\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\raw-skt\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\raw-file\. -ID:\test_lib\libweb4.3\libwebsockets\lib\roles\listen\. -ID:\test_lib\libweb4.3\libwebsockets\lib\event-libs\. -ID:\test_lib\libweb4.3\libwebsockets\lib\event-libs\poll\..\poll -IC:\PROGRA~1\OPENSS~1\include /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /DNDEBUG   /W3 /WX /Zc:preprocessor /wd5105 /FoCMakeFiles\websockets.dir\roles\ws\ext\extension-permessage-deflate.c.obj /FdCMakeFiles\websockets.dir\websockets.pdb /FS -c D:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.c

extension-permessage-deflate.c


**D:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.c(431): error C2220: the following warning is treated as an error
D:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.c(431): warning C4013: 'deflatePending' undefined; assuming extern returning int
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe' : return code '0x2'**

**Comment by lws-team** [comment]
How about this?  You might need to do it by hand due to the windows line endings in the existing file

```
diff --git a/win32port/zlib/zlib.h b/win32port/zlib/zlib.h
index cba7ab2fb3..e6b7fae510 100644
--- a/win32port/zlib/zlib.h
+++ b/win32port/zlib/zlib.h
@@ -664,6 +664,9 @@ ZEXTERN int ZEXPORT deflateParams OF((z_streamp strm,
    strm->avail_out was zero.
 */
 
+ZEXTERN int ZEXPORT deflatePending OF((unsigned *pending,^M
+                                      int *bits, z_streamp strm));^M
+^M
 ZEXTERN int ZEXPORT deflateTune OF((z_streamp strm,
                                     int good_length,
                                     int max_lazy,
```

**Comment by sush126** [comment]
i have added below declration in zlib.h but compiler gives error:
ZEXTERN int ZEXPORT deflatePending OF((unsigned *pending,
                                      int *bits, z_streamp strm));
                                      
Error:

extension-permessage-deflate.c
D:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.c(431): error C2220: the following warning is treated as an error
D:\test_lib\libweb4.3\libwebsockets\lib\roles\ws\ext\extension-permessage-deflate.c(431): warning C4133: 'function': incompatible types - from 'z_stream *' to 'unsigned int *'

**Comment by lws-team** [comment]
Ugh... ancient C style used in zlib has the arguments disordered... this (instead of the last patch) should fix it

```
diff --git a/win32port/zlib/deflate.c b/win32port/zlib/deflate.c
index 0f6fc1e049..9fbc583210 100644
--- a/win32port/zlib/deflate.c
+++ b/win32port/zlib/deflate.c
@@ -398,9 +398,9 @@ int ZEXPORT deflateSetHeader (strm, head)
 
 /* ========================================================================= */
 int ZEXPORT deflatePending (strm, pending, bits)
+    z_streamp strm;
     unsigned *pending;
     int *bits;
-    z_streamp strm;
 {
     if (strm == Z_NULL || strm->state == Z_NULL) return Z_STREAM_ERROR;
     *pending = strm->state->pending;
diff --git a/win32port/zlib/zlib.h b/win32port/zlib/zlib.h
index cba7ab2fb3..3c83433233 100644
--- a/win32port/zlib/zlib.h
+++ b/win32port/zlib/zlib.h
@@ -664,6 +664,8 @@ ZEXTERN int ZEXPORT deflateParams OF((z_streamp strm,
    strm->avail_out was zero.
 */
 
+ZEXTERN int ZEXPORT deflatePending OF((z_streamp strm, unsigned *pending, int *bits));
+
 ZEXTERN int ZEXPORT deflateTune OF((z_streamp strm,
                                     int good_length,
                                     int max_lazy,
```

**Comment by sush126** [comment]
yes added your changes and done clean build but it give linking error:


CMakeFiles/websockets_shared.dir/plat/windows/windows-fds.c.obj CMakeFiles/websockets_shared.dir/plat/windows/windows-file.c.obj CMakeFiles/websockets_shared.dir/plat/windows/windows-init.c.obj CMakeFiles/websockets_shared.dir/plat/windows/windows-misc.c.obj CMakeFiles/websockets_shared.dir/plat/windows/windows-pipe.c.obj CMakeFiles/websockets_shared.dir/plat/windows/windows-plugins.c.obj CMakeFiles/websockets_shared.dir/plat/windows/windows-service.c.obj CMakeFiles/websockets_shared.dir/plat/windows/windows-sockets.c.obj CMakeFiles/websockets_shared.dir/__/win32port/win32helpers/gettimeofday.c.obj CMakeFiles/websockets_shared.dir/tls/tls.c.obj CMakeFiles/websockets_shared.dir/tls/tls-network.c.obj CMakeFiles/websockets_shared.dir/tls/tls-sessions.c.obj CMakeFiles/websockets_shared.dir/tls/openssl/openssl-tls.c.obj CMakeFiles/websockets_shared.dir/tls/openssl/openssl-x509.c.obj CMakeFiles/websockets_shared.dir/tls/openssl/openssl-ssl.c.obj CMakeFiles/websockets_shared.dir/tls/openssl/openssl-session.c.obj CMakeFiles/websockets_shared.dir/tls/tls-server.c.obj CMakeFiles/websockets_shared.dir/tls/openssl/openssl-server.c.obj CMakeFiles/websockets_shared.dir/tls/tls-client.c.obj CMakeFiles/websockets_shared.dir/tls/openssl/openssl-client.c.obj CMakeFiles/websockets_shared.dir/core/alloc.c.obj CMakeFiles/websockets_shared.dir/core/buflist.c.obj CMakeFiles/websockets_shared.dir/core/context.c.obj CMakeFiles/websockets_shared.dir/core/lws_dll2.c.obj CMakeFiles/websockets_shared.dir/core/lws_map.c.obj CMakeFiles/websockets_shared.dir/core/libwebsockets.c.obj CMakeFiles/websockets_shared.dir/core/logs.c.obj CMakeFiles/websockets_shared.dir/core/vfs.c.obj CMakeFiles/websockets_shared.dir/misc/base64-decode.c.obj CMakeFiles/websockets_shared.dir/misc/prng.c.obj CMakeFiles/websockets_shared.dir/misc/lws-ring.c.obj CMakeFiles/websockets_shared.dir/misc/cache-ttl/lws-cache-ttl.c.obj CMakeFiles/websockets_shared.dir/misc/cache-ttl/heap.c.obj CMakeFiles/websockets_shared.dir/misc/cache-ttl/file.c.obj CMakeFiles/websockets_shared.dir/misc/dir.c.obj CMakeFiles/websockets_shared.dir/misc/lwsac/lwsac.c.obj CMakeFiles/websockets_shared.dir/misc/lwsac/cached-file.c.obj CMakeFiles/websockets_shared.dir/misc/sha-1.c.obj CMakeFiles/websockets_shared.dir/misc/lejp.c.obj CMakeFiles/websockets_shared.dir/system/system.c.obj CMakeFiles/websockets_shared.dir/core-net/dummy-callback.c.obj CMakeFiles/websockets_shared.dir/core-net/output.c.obj CMakeFiles/websockets_shared.dir/core-net/close.c.obj CMakeFiles/websockets_shared.dir/core-net/network.c.obj CMakeFiles/websockets_shared.dir/core-net/vhost.c.obj CMakeFiles/websockets_shared.dir/core-net/pollfd.c.obj CMakeFiles/websockets_shared.dir/core-net/service.c.obj CMakeFiles/websockets_shared.dir/core-net/sorted-usec-list.c.obj CMakeFiles/websockets_shared.dir/core-net/wsi.c.obj CMakeFiles/websockets_shared.dir/core-net/wsi-timeout.c.obj CMakeFiles/websockets_shared.dir/core-net/adopt.c.obj CMakeFiles/websockets_shared.dir/roles/pipe/ops-pipe.c.obj CMakeFiles/websockets_shared.dir/core-net/state.c.obj CMakeFiles/websockets_shared.dir/core-net/client/client.c.obj CMakeFiles/websockets_shared.dir/core-net/client/connect.c.obj CMakeFiles/websockets_shared.dir/core-net/client/connect2.c.obj CMakeFiles/websockets_shared.dir/core-net/client/connect3.c.obj CMakeFiles/websockets_shared.dir/core-net/client/connect4.c.obj CMakeFiles/websockets_shared.dir/core-net/client/sort-dns.c.obj CMakeFiles/websockets_shared.dir/core-net/client/conmon.c.obj CMakeFiles/websockets_shared.dir/roles/http/header.c.obj CMakeFiles/websockets_shared.dir/roles/http/date.c.obj CMakeFiles/websockets_shared.dir/roles/http/parsers.c.obj CMakeFiles/websockets_shared.dir/roles/http/server/server.c.obj CMakeFiles/websockets_shared.dir/roles/http/server/lws-spa.c.obj CMakeFiles/websockets_shared.dir/roles/http/cookie.c.obj CMakeFiles/websockets_shared.dir/roles/http/server/lejp-conf.c.obj CMakeFiles/websockets_shared.dir/roles/h1/ops-h1.c.obj CMakeFiles/websockets_shared.dir/roles/h2/http2.c.obj CMakeFiles/websockets_shared.dir/roles/h2/hpack.c.obj CMakeFiles/websockets_shared.dir/roles/h2/ops-h2.c.obj CMakeFiles/websockets_shared.dir/roles/ws/ops-ws.c.obj CMakeFiles/websockets_shared.dir/roles/ws/client-ws.c.obj CMakeFiles/websockets_shared.dir/roles/ws/client-parser-ws.c.obj CMakeFiles/websockets_shared.dir/roles/ws/server-ws.c.obj CMakeFiles/websockets_shared.dir/roles/ws/ext/extension.c.obj CMakeFiles/websockets_shared.dir/roles/ws/ext/extension-permessage-deflate.c.obj CMakeFiles/websockets_shared.dir/roles/raw-skt/ops-raw-skt.c.obj CMakeFiles/websockets_shared.dir/roles/raw-file/ops-raw-file.c.obj CMakeFiles/websockets_shared.dir/roles/listen/ops-listen.c.obj CMakeFiles/websockets_shared.dir/roles/http/client/client-http.c.obj CMakeFiles/websockets_shared.dir/event-libs/poll/poll.c.obj CMakeFiles/websockets_shared.dir/__/win32port/version.rc.res
   Creating library websockets.lib and object websockets.exp
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflate referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflateEnd referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol inflate referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol inflateEnd referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflatePending referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflateInit2_ referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol inflateInit2_ referenced in function lws_extension_callback_pm_deflate
..\bin\websockets.dll : fatal error LNK1120: 7 unresolved externals
NMAKE : fatal error U1077: 'D:\software\cmake-3.15.3-win64-x64\bin\cmake.exe' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by Littlebigdondon** [comment]
Looks like the correct path for the bundled zlib should actually be one step above `WIN32_HELPERS_PATH` (i.e. `
include_directories(../../${WIN32_HELPERS_PATH} ../../${WIN32_HELPERS_PATH}/../zlib)` or similar). 

However, I do believe there is a problem that occurs before this incorrect path. When simply setting `LWS_WITHOUT_EXTENSIONS OFF`, LWS's top-level CMakeLists.txt will still hit the `find_package(ZLIB REQUIRED)`  command since it occurs before the platform-specific subdirectories are included (which _would_ set `ZLIB_FOUND` due to `LWS_WITH_BUNDLED_ZLIB` being true; thereby skipping the attempt to find the package externally). It just seems like that Windows-specific inclusion of the bundled zlib happens too late.

If I do force `ZLIB_FOUND 1` to skip the `find_package` call, AND set the correct path to the bundled zlib, then I do finally get to the linker errors given by @sush126. I tried these manual fixes on both 4.3.2 and the current main branch (commit [f9d1f25](https://github.com/warmcat/libwebsockets/commit/f9d1f25abe896b9fa1de780e4a5cb41116926a29)).

Hope that is helpful.
