### ISSUE TITLE
Windows ssl crash

### ISSUE THREAD

**Issue by Libco** [warmcat/libwebsockets#360]
I have an issue when using ssl on windows - it works fine on linux. Using newest commit at this time.
- What happens is, that its crashing on lws_ssl_pending function [ssl.c]. 
- It handles the request fine, then it closes the connection with lws_ssl_close [ssl.c] where the wsi->ssl is set to NULL. 
- But then the lws_free_wsi [libwebsockets.c] is called that calls lws_free(wsi) which deallocates everything so the wsi->ssl it now set to some random address which than goes to the lws_ssl_pending where it only checks for if (!wsi->ssl) which is false because its not null.

- Works fine if i put wsi->ssl = NULL; at the end of lws_free_wsi function, but not sure if that is the way to fix it...

**Comment by lws-team** [comment]
That last bit is definitely not fixing anything... as you thought the problem is definitely that something else still thinks the dead wsi is alive and dereferences it at all.

I looked at it and pushed a small patch but unclear if related.

The crash backtrace would probably help.

**Comment by Libco** [comment]
It's still doing it.

>	ssleay32.dll!SSL_pending(const ssl_st * s) Line 874	C
 	something.exe!lws_ssl_pending(lws * wsi) Line 487	C
 	something.exe!lws_service_fd(lws_context * context, lws_pollfd * pollfd) Line 501	C
 	something.exe!lws_plat_service(lws_context * context, int timeout_ms) Line 209	C
 	something.exe!lws_service(lws_context * context, int timeout_ms) Line 681	C

**Comment by lws-team** [comment]
I pushed something else try.

**Comment by Libco** [comment]
still the same. the n variable from lws_server_socket_service() in service.c is 0. Also for some reason when i open it it microsoft edge browser the n is 1 and then its crashes at 

>	something.exe!lws_ssl_remove_wsi_from_buffered_list(lws_context * context, lws * wsi) Line 424	C
 	something.exe!lws_close_and_free_session(lws_context * context, lws * wsi, lws_close_status reason) Line 219	C
 	something.exe!lws_service_fd(lws_context * context, lws_pollfd * pollfd) Line 637	C
 	something.exe!lws_plat_service(lws_context * context, int timeout_ms) Line 209	C
 	something.exe!lws_service(lws_context * context, int timeout_ms) Line 685	C

**Comment by lws-team** [comment]
Sorry that last fix is a real problem, but I didn't fix it enough.  I pushed a one-liner that should make the edge thing go away.  I also fixed some other related error paths, but I haven't got much clue if these are attacking your problem.  Could you maybe make sure _DEBUG is defined, and turn up the logging and see if the sequence is clearer?

**Comment by Libco** [comment]
Actually it seems to be working now (both issues). Will test it more later, but i think you can close this issue. Thanks for the quick fixes.

**Comment by lws-team** [comment]
Good news... please reopen if it's coming back.
