### ISSUE TITLE
Connecting to an invalid websocket URI will trigger assertion

### ISSUE THREAD

**Issue by dumganhar** [warmcat/libwebsockets#394]
### Libwebsockets Version I used

The latest master branch .

### How to reproduce?

Uses libwebsockets as a client, and connect to `ws://invalidurl.com`
Code will go to

```c++
int
lws_client_interpret_server_handshake(struct lws *wsi)
{
...
...
	if (lws_hdr_total_length(wsi, WSI_TOKEN_ACCEPT) == 0) {
		lwsl_info("no ACCEPT\n");
		p = lws_hdr_simple_ptr(wsi, WSI_TOKEN_HTTP);
		isErrorCodeReceived = 1;
		goto bail3;   // will go to here
	}
...
...

bail3:
	lws_free_set_NULL(wsi->u.ws.rx_user_buffer);   // will go to here, since wsi->u is a union, free the memory of wsi->u.ws.rx_user_buffer will make `wsi->u.hdr.ah` to be nullptr
	close_reason = LWS_CLOSE_STATUS_NOSTATUS;

bail2:
...
...
	/* free up his parsing allocations */
	lws_free_header_table(wsi);   // will go to here
	lws_close_free_wsi(wsi, close_reason);

	return 1;
}

```

```c++
int lws_free_header_table(struct lws *wsi)
{
	struct lws_context *context = wsi->context;

	lwsl_debug("%s: wsi %p: ah %p (count = %d)\n", __func__, (void *)wsi,
		 (void *)wsi->u.hdr.ah, context->ah_count_in_use);

	assert(wsi->u.hdr.ah); // assertion happens, how to fix it?
	if (!wsi->u.hdr.ah)
		return 0;
```

**Comment by lws-team** [comment]
Actually I can't reproduce with the test client.  Can you?

```
[agreen@build build]$ libwebsockets-test-client nope-ccv
libwebsockets test client
(C) Copyright 2010-2015 Andy Green <andy@warmcat.com> licensed under LGPL2.1
[1452380102:2020] NOTICE: Initial logging level 7
[1452380102:2020] NOTICE: Libwebsockets version: 1.6.0 5eeb4bd
[1452380102:2020] NOTICE: IPV6 not compiled in
[1452380102:2020] NOTICE: libev support compiled in but disabled
[1452380102:2020] NOTICE:  mem: platform fd map:  8192 bytes
[1452380102:2021] NOTICE:  mem: per-conn:          464 bytes + protocol rx buf
[1452380102:2021] NOTICE:  canonical_hostname = build.warmcat.com
[1452380102:2156] NOTICE: dumb: connecting
[1452380102:6397] NOTICE: mirror: connecting
[1452380104:1443] NOTICE: dumb: connecting
[1452380104:1473] NOTICE: mirror: connecting
[1452380106:1523] NOTICE: dumb: connecting
[1452380106:1557] NOTICE: mirror: connecting
[1452380108:1619] NOTICE: dumb: connecting
[1452380108:1649] NOTICE: mirror: connecting
^C[1452380109:9161] ERR: Exiting
```

**Comment by dumganhar** [comment]
@lws-team 

libwebsockets-test-client also has the problem, please see the log following, I tested it on OSX10.11

```
JamesdeMac-mini:build james$ bin/libwebsockets-test-client ws://invalid.url.com -p 80
libwebsockets test client
(C) Copyright 2010-2015 Andy Green <andy@warmcat.com> licensed under LGPL2.1
[1452401104:8042] NOTICE: Initial logging level 7
[1452401104:8042] NOTICE: Libwebsockets version: 1.6.0 0c7e5a9
[1452401104:8042] NOTICE: IPV6 not compiled in
[1452401104:8042] NOTICE: libev support not compiled in
[1452401104:8043] NOTICE:  mem: platform fd map:  2048 bytes
[1452401104:8043] NOTICE:  mem: per-conn:          312 bytes + protocol rx buf
[1452401104:8043] NOTICE:  canonical_hostname = JamesdeMac-mini.local
[1452401104:8043] NOTICE: dumb: connecting
[1452401105:1914] NOTICE: mirror: connecting
[1452401105:8500] ERR: dumb: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452401105:8501] WARN: lws_free_header_table: wsi 0x7ff3ea403530: ah 0x7ff3ea807a00 (count = 2)
[1452401105:8502] ERR: mirror: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452401105:8502] WARN: lws_free_header_table: wsi 0x7ff3ea5005b0: ah 0x7ff3ea807e58 (count = 1)
[1452401106:3519] NOTICE: dumb: connecting
[1452401106:9763] ERR: dumb: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452401106:9764] WARN: lws_free_header_table: wsi 0x7ff3ea5005b0: ah 0x7ff3ea807a00 (count = 1)
[1452401107:4796] NOTICE: mirror: connecting
[1452401108:1003] ERR: mirror: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452401108:1004] WARN: lws_free_header_table: wsi 0x7ff3ea5005b0: ah 0x0 (count = 1)
[1452401108:1004] NOTICE: dumb: connecting
libwebsockets-test-client(7169,0x7fff7dc9d000) malloc: *** error for object 0x7ff3ea807e58: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by dumganhar** [comment]
@lws-team 
Any updates? Could you reproduce it now?
Or could you please look at the logic I commented?

**Comment by lws-team** [comment]
I will look at it soon.

**Comment by dumganhar** [comment]
Thanks a lot. :+1:  
I'll keep online and wait for the result. :)

**Comment by lws-team** [comment]
Whatever this problem is, it's not triggered on Linux.

```
[agreen@build build]$ libwebsockets-test-client ws://invalid.url.com -p 80
libwebsockets test client
(C) Copyright 2010-2015 Andy Green <andy@warmcat.com> licensed under LGPL2.1
[1452485320:0464] NOTICE: Initial logging level 7
[1452485320:0464] NOTICE: Libwebsockets version: 1.6.0 1c7ac03
[1452485320:0464] NOTICE: IPV6 not compiled in
[1452485320:0464] NOTICE: libev support compiled in but disabled
[1452485320:0464] NOTICE:  mem: platform fd map:  8192 bytes
[1452485320:0464] NOTICE:  mem: per-conn:          480 bytes + protocol rx buf
[1452485320:0464] NOTICE:  canonical_hostname = build.warmcat.com
[1452485320:0572] NOTICE: dumb: connecting
[1452485320:3849] NOTICE: mirror: connecting
[1452485322:3888] NOTICE: dumb: connecting
[1452485322:3906] NOTICE: mirror: connecting
[1452485324:3945] NOTICE: dumb: connecting
[1452485324:3963] NOTICE: mirror: connecting
[1452485326:3999] NOTICE: dumb: connecting
[1452485326:4016] NOTICE: mirror: connecting
[1452485328:4048] NOTICE: dumb: connecting
[1452485328:4068] NOTICE: mirror: connecting
[1452485330:4107] NOTICE: dumb: connecting
[1452485330:4125] NOTICE: mirror: connecting
[1452485332:4159] NOTICE: dumb: connecting
[1452485332:4177] NOTICE: mirror: connecting
^C[1452485332:9436] ERR: Exiting
[1452485332:9436] NOTICE: lws_context_destroy
```

**Comment by dumganhar** [comment]
But why didn't it trigger CONNECTION_ERROR？Your output seemed always being connecting.

**Comment by lws-team** [comment]
The test-client uses the CLOSE callback to understand it needs to retry the connection.  It can close (and want to reconnect) for other reasons than CONNECTION_ERROR.

Hoeever it doesn't fire a CONNECTION_ERROR if it couldn't even complete the dns.  I'll add a patch for that since I guess it makes sense it should.

**Comment by lws-team** [comment]
Hm... does your dns fail, if you try to resolve something nonexistent, or redirect you somewhere?

**Comment by lws-team** [comment]
And there is no need to do CONNECTION_ERROR it seems.  For these early failures, client_connect() returns NULL, so the caller knows he failed.

**Comment by lws-team** [comment]
It seems there's something quite different about your error flow.  I can see

 - using a proxy

 - dns that redirects to a fixed address on errors

could change the flow... can you let me know if either are the case for you, or anything else unusual about your network environment?

**Comment by dumganhar** [comment]
> using a proxy

I didn't.

> dns that redirects to a fixed address on errors

I didn't, and the network is ok, I could visit any website.

Yesterday, I encountered the biggest difficulty in my life. So I'll be away for some days.
I'll be much appreciate if you could find out something according what i provided.
Thank you.

**Comment by lws-team** [comment]
Sorry but reviewing just the first few lines of your very first post, what you're saying doesn't seem possible.

You're **both** saying that

1) the dns address does not exist, in which case we can't connect to anything, **and** that

2) we presumably connected to it and are interpreting the nonexistent server's response when there is a problem.

And the things that could square that circle, dns lookup fail redirect, or proxy, are also ruled out.

Not only can I not reproduce it, I can't imagine how to get that situation if everything is true.  This code is all posix sockets there can't really be this kind of bug in there as far as my imagination can manage to go.

I guess for you the situation is real somehow, so maybe there is something special about your platform or network environment, or I have a bug "beyond my feeble imagination" that nobody else hit until now.  If after clearing your difficulties you want to come back to this problem, please reopen this bug, and

 - build the library with _DEBUG defined

 - run the test client with -d65535 and send the logs.

 - use wireshark or tcpdump and show exactly what happens on the wire during the test.

Good luck with your other difficulties in the meanwhile.

**Comment by lws-team** [comment]
Whatever the logical problems describing or reproducing this, the actual symptom you reportin the first comment has been fixed from another direction

https://github.com/warmcat/libwebsockets/commit/83080734640aceec79d46c01be7fde7c70a6a01c

**Comment by dumganhar** [comment]
> Whatever the logical problems describing or reproducing this, the actual symptom you reportin the first comment has been fixed from another direction

Thank you, I'll check it now.

BTW, glad to hear that `permessage deflate` is supported now.
I tested it yesterday, but there are some cases of compression didn't pass `Autobahn`.

**Comment by dumganhar** [comment]
> Whatever the logical problems describing or reproducing this, the actual symptom you reportin the first comment has been fixed from another direction

Hi, @lws-team , 8308073 didn't fix the `assertion` problem. I enabled `log_level` to 65535, could you help to see the log since I'm not familiar with `libwebsockets` and it's hard for me to check out the problem.

```
JS: Cocos2d-JS v3.10
[WebSocket::init] _host: invalid.url.com, _port: 80, _path: /
WebSocket thread start, helper instance: 0x6100000a2c40
NOTICE: Initial logging level 65535

NOTICE: Libwebsockets version: 1.6.0 8308073

NOTICE: IPV6 not compiled in

NOTICE: libev support not compiled in

INFO:  LWS_MAX_HEADER_LEN: 1024

INFO:  LWS_MAX_PROTOCOLS: 5

INFO:  SPEC_LATEST_SUPPORTED: 13

INFO:  AWAITING_TIMEOUT: 5

INFO:  sizeof (*info): 208

INFO:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'

INFO:  LWS_MAX_ZLIB_CONN_BUFFER: 65536

INFO:  mem: context:          4704 bytes

INFO:  mem: http hdr rsvd:   34176 bytes ((1024 + 1112) x 16)

INFO:  mem: pollfd map:      38912

NOTICE:  mem: platform fd map: 38912 bytes

INFO:  LWS_MAX_EXTENSIONS_ACTIVE: 3

NOTICE:  mem: per-conn:          336 bytes + protocol rx buf

DEBUG: lws_allocate_header_table: wsi 0x3649d0: ah 0x0

DEBUG: lws_allocate_header_table: wsi 0x3649d0: ah 0x1042000: count 1 (on exit)

CLIENT: lws_client_connect: direct conn

CLIENT: lws_client_connect_2

CLIENT: lws_client_connect_2: address invalid.url.com

CLIENT: nonblocking connect retry

CLIENT: lws_client_connect_2

CLIENT: lws_client_connect_2: address invalid.url.com

CLIENT: connected

PARSER: WSI_TOKEN_NAME_PART 'H' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'T' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'T' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'P' (mode=12)

PARSER: WSI_TOKEN_NAME_PART '/' (mode=12)

PARSER: WSI_TOKEN_NAME_PART '1' (mode=12)

PARSER: WSI_TOKEN_NAME_PART '.' (mode=12)

PARSER: WSI_TOKEN_NAME_PART '1' (mode=12)

PARSER: WSI_TOKEN_NAME_PART ' ' (mode=12)

PARSER: known hdr 15

PARSER: WSI_TOK_(15) '3'

PARSER: WSI_TOK_(15) '0'

PARSER: WSI_TOK_(15) '1'

PARSER: WSI_TOK_(15) ' '

PARSER: WSI_TOK_(15) 'M'

PARSER: WSI_TOK_(15) 'o'

PARSER: WSI_TOK_(15) 'v'

PARSER: WSI_TOK_(15) 'e'

PARSER: WSI_TOK_(15) 'd'

PARSER: WSI_TOK_(15) ' '

PARSER: WSI_TOK_(15) 'P'

PARSER: WSI_TOK_(15) 'e'

PARSER: WSI_TOK_(15) 'r'

PARSER: WSI_TOK_(15) 'm'

PARSER: WSI_TOK_(15) 'a'

PARSER: WSI_TOK_(15) 'n'

PARSER: WSI_TOK_(15) 'e'

PARSER: WSI_TOK_(15) 'n'

PARSER: WSI_TOK_(15) 't'

PARSER: WSI_TOK_(15) 'l'

PARSER: WSI_TOK_(15) 'y'

PARSER: WSI_TOK_(15) '
'

PARSER: *

PARSER: WSI_TOKEN_SKIPPING_SAW_CR '
'

PARSER: WSI_TOKEN_NAME_PART 'S' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'r' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'v' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'r' (mode=12)

PARSER: WSI_TOKEN_NAME_PART ':' (mode=12)

PARSER: known hdr 65

PARSER: WSI_TOK_(65) ' '

PARSER: WSI_TOK_(65) 'n'

PARSER: WSI_TOK_(65) 'g'

PARSER: WSI_TOK_(65) 'i'

PARSER: WSI_TOK_(65) 'n'

PARSER: WSI_TOK_(65) 'x'

PARSER: WSI_TOK_(65) '/'

PARSER: WSI_TOK_(65) '1'

PARSER: WSI_TOK_(65) '.'

PARSER: WSI_TOK_(65) '6'

PARSER: WSI_TOK_(65) '.'

PARSER: WSI_TOK_(65) '3'

PARSER: WSI_TOK_(65) '
'

PARSER: *

PARSER: WSI_TOKEN_SKIPPING_SAW_CR '
'

PARSER: WSI_TOKEN_NAME_PART 'D' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'a' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART ':' (mode=12)

PARSER: known hdr 29

PARSER: WSI_TOK_(29) ' '

PARSER: WSI_TOK_(29) 'W'

PARSER: WSI_TOK_(29) 'e'

PARSER: WSI_TOK_(29) 'd'

PARSER: WSI_TOK_(29) ','

PARSER: WSI_TOK_(29) ' '

PARSER: WSI_TOK_(29) '1'

PARSER: WSI_TOK_(29) '3'

PARSER: WSI_TOK_(29) ' '

PARSER: WSI_TOK_(29) 'J'

PARSER: WSI_TOK_(29) 'a'

PARSER: WSI_TOK_(29) 'n'

PARSER: WSI_TOK_(29) ' '

PARSER: WSI_TOK_(29) '2'

PARSER: WSI_TOK_(29) '0'

PARSER: WSI_TOK_(29) '1'

PARSER: WSI_TOK_(29) '6'

PARSER: WSI_TOK_(29) ' '

PARSER: WSI_TOK_(29) '0'

PARSER: WSI_TOK_(29) '8'

PARSER: WSI_TOK_(29) ':'

PARSER: WSI_TOK_(29) '4'

PARSER: WSI_TOK_(29) '9'

PARSER: WSI_TOK_(29) ':'

PARSER: WSI_TOK_(29) '0'

PARSER: WSI_TOK_(29) '9'

PARSER: WSI_TOK_(29) ' '

PARSER: WSI_TOK_(29) 'G'

PARSER: WSI_TOK_(29) 'M'

PARSER: WSI_TOK_(29) 'T'

PARSER: WSI_TOK_(29) '
'

PARSER: *

PARSER: WSI_TOKEN_SKIPPING_SAW_CR '
'

PARSER: WSI_TOKEN_NAME_PART 'C' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'o' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART '-' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'T' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'y' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'p' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART ':' (mode=12)

PARSER: known hdr 28

PARSER: WSI_TOK_(28) ' '

PARSER: WSI_TOK_(28) 't'

PARSER: WSI_TOK_(28) 'e'

PARSER: WSI_TOK_(28) 'x'

PARSER: WSI_TOK_(28) 't'

PARSER: WSI_TOK_(28) '/'

PARSER: WSI_TOK_(28) 'h'

PARSER: WSI_TOK_(28) 't'

PARSER: WSI_TOK_(28) 'm'

PARSER: WSI_TOK_(28) 'l'

PARSER: WSI_TOK_(28) '
'

PARSER: *

PARSER: WSI_TOKEN_SKIPPING_SAW_CR '
'

PARSER: WSI_TOKEN_NAME_PART 'C' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'o' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART '-' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'L' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'g' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'h' (mode=12)

PARSER: WSI_TOKEN_NAME_PART ':' (mode=12)

PARSER: known hdr 27

PARSER: WSI_TOK_(27) ' '

PARSER: WSI_TOK_(27) '1'

PARSER: WSI_TOK_(27) '8'

PARSER: WSI_TOK_(27) '4'

PARSER: WSI_TOK_(27) '
'

PARSER: *

PARSER: WSI_TOKEN_SKIPPING_SAW_CR '
'

PARSER: WSI_TOKEN_NAME_PART 'C' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'o' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'e' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'c' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'i' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'o' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART ':' (mode=12)

PARSER: known hdr 4

PARSER: WSI_TOK_(4) ' '

PARSER: WSI_TOK_(4) 'k'

PARSER: WSI_TOK_(4) 'e'

PARSER: WSI_TOK_(4) 'e'

PARSER: WSI_TOK_(4) 'p'

PARSER: WSI_TOK_(4) '-'

PARSER: WSI_TOK_(4) 'a'

PARSER: WSI_TOK_(4) 'l'

PARSER: WSI_TOK_(4) 'i'

PARSER: WSI_TOK_(4) 'v'

PARSER: WSI_TOK_(4) 'e'

PARSER: WSI_TOK_(4) '
'

PARSER: *

PARSER: WSI_TOKEN_SKIPPING_SAW_CR '
'

PARSER: WSI_TOKEN_NAME_PART 'L' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'o' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'c' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'a' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 't' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'i' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'o' (mode=12)

PARSER: WSI_TOKEN_NAME_PART 'n' (mode=12)

PARSER: WSI_TOKEN_NAME_PART ':' (mode=12)

PARSER: known hdr 59

PARSER: WSI_TOK_(59) ' '

PARSER: WSI_TOK_(59) 'h'

PARSER: WSI_TOK_(59) 't'

PARSER: WSI_TOK_(59) 't'

PARSER: WSI_TOK_(59) 'p'

PARSER: WSI_TOK_(59) ':'

PARSER: WSI_TOK_(59) '/'

PARSER: WSI_TOK_(59) '/'

PARSER: WSI_TOK_(59) 'l'

PARSER: WSI_TOK_(59) 'y'

PARSER: WSI_TOK_(59) 'r'

PARSER: WSI_TOK_(59) 'i'

PARSER: WSI_TOK_(59) 'c'

PARSER: WSI_TOK_(59) 's'

PARSER: WSI_TOK_(59) '.'

PARSER: WSI_TOK_(59) 'u'

PARSER: WSI_TOK_(59) 'r'

PARSER: WSI_TOK_(59) 'l'

PARSER: WSI_TOK_(59) '.'

PARSER: WSI_TOK_(59) 'c'

PARSER: WSI_TOK_(59) 'o'

PARSER: WSI_TOK_(59) 'm'

PARSER: WSI_TOK_(59) '/'

PARSER: WSI_TOK_(59) '
'

PARSER: *

PARSER: WSI_TOKEN_SKIPPING_SAW_CR '
'

PARSER: WSI_TOKEN_NAME_PART '
' (mode=12)

PARSER: WSI_TOKEN_NAME_PART '
' (mode=12)

PARSER: known hdr 8

INFO: no ACCEPT

WebSocket (0x610000102880) onConnectionError ...
INFO: closing connection due to bail2 connection error

DEBUG: lws_free_header_table: wsi 0x3649d0: ah 0x0 (count = 1)

Assertion failed: (wsi->u.hdr.ah), function lws_free_header_table, file /Users/james/Project/libwebsockets/lib/parsers.c, line 118.
```

**Comment by dumganhar** [comment]
I noticed that there is a `CLIENT: connected`, but it should not be connected state, right?

**Comment by lws-team** [comment]
hm this is something unrelated to invalid dns address.  But it does need solving.

```
PARSER: WSI_TOK_(15) '3'

PARSER: WSI_TOK_(15) '0'

PARSER: WSI_TOK_(15) '1'

PARSER: WSI_TOK_(15) ' '

PARSER: WSI_TOK_(15) 'M'

PARSER: WSI_TOK_(15) 'o'

PARSER: WSI_TOK_(15) 'v'

PARSER: WSI_TOK_(15) 'e'

PARSER: WSI_TOK_(15) 'd'

PARSER: WSI_TOK_(15) ' '

PARSER: WSI_TOK_(15) 'P'

PARSER: WSI_TOK_(15) 'e'

PARSER: WSI_TOK_(15) 'r'

PARSER: WSI_TOK_(15) 'm'

PARSER: WSI_TOK_(15) 'a'

PARSER: WSI_TOK_(15) 'n'

PARSER: WSI_TOK_(15) 'e'

PARSER: WSI_TOK_(15) 'n'

PARSER: WSI_TOK_(15) 't'

PARSER: WSI_TOK_(15) 'l'

PARSER: WSI_TOK_(15) 'y'

PARSER: WSI_TOK_(15) '
```

Basically something returns a 301 response, lws doesn't deal with that and we blow the assert in the cleanup for the failed negotiation.

**Comment by dumganhar** [comment]
@lws-team ,thank you for reopen this issue.
If you finish to fix it, just let me know, I'll check it ASAP.

**Comment by lws-team** [comment]
You have a transparent nginx 1.6.3 proxy you did not know about that is accepting the tcp connection and redirecting us.  That's why you were sering 'impossible things'.

But 1) lws doesn't know about redirect, and 2) he cleans up the allocated headers twice on that path.  Both are real problems.

**Comment by dumganhar** [comment]
BTW, the old version `1.3` didn't has this problem.

**Comment by dumganhar** [comment]
> You have a transparent nginx 1.6.3 proxy you did not know about that is accepting the tcp connection and redirecting us. That's why you were sering 'impossible things'.

In fact, I didn't use a `nginx` proxy.  I just use a `Router` to share a Wifi network for some devices.

> But 1) lws doesn't know about redirect, and 2) he cleans up the allocated headers twice on that path. Both are real problems.

So could this be fixed easily? :)

**Comment by dumganhar** [comment]
So what you mean is that:

`invalid.url.com` uses a nginx proxy.

Yep, I curl it and got the following logs:

```
james@James-Chen cocos2d-x$ curl -I invalid.url.com
HTTP/1.1 301 Moved Permanently
Server: nginx/1.6.3
Date: Wed, 13 Jan 2016 09:30:22 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: http://lyrics.url.com/
```

**Comment by dumganhar** [comment]
I changed to connect to `ws://invalidurl.com`, and it didn't assert now.
But the error message will be triggered twice, any thoughts?

```

{
	gl.supports_vertex_array_object: true
	cocos2d.x.version: cocos2d-x-3.10
	gl.vendor: NVIDIA Corporation
	gl.supports_PVRTC: false
	gl.renderer: NVIDIA GeForce GT 650M OpenGL Engine
	cocos2d.x.compiled_with_profiler: false
	gl.max_texture_size: 16384
	gl.supports_ETC1: false
	gl.supports_BGRA8888: false
	cocos2d.x.build_type: DEBUG
	gl.supports_discard_framebuffer: false
	gl.supports_NPOT: true
	gl.supports_S3TC: true
	gl.version: 2.1 NVIDIA-10.8.14 310.42.15f01
	gl.supports_ATITC: false
	gl.max_texture_units: 16
	cocos2d.x.compiled_with_gl_state_cache: true
}


cocos2d: fullPathForFilename: No file found at script/jsb_prepare.jsc. Possible missing file.
cocos2d: fullPathForFilename: No file found at script/jsb_boot.jsc. Possible missing file.
JS: Cocos2d-JS v3.10
[WebSocket::init] _host: invalidurl.com, _port: 80, _path: /
WebSocket thread start, helper instance: 0x6100000b3500
NOTICE: Initial logging level 65535

NOTICE: Libwebsockets version: 1.6.0 8308073

NOTICE: IPV6 not compiled in

NOTICE: libev support not compiled in

INFO:  LWS_MAX_HEADER_LEN: 1024

INFO:  LWS_MAX_PROTOCOLS: 5

INFO:  SPEC_LATEST_SUPPORTED: 13

INFO:  AWAITING_TIMEOUT: 5

INFO:  sizeof (*info): 208

INFO:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'

INFO:  LWS_MAX_ZLIB_CONN_BUFFER: 65536

INFO:  mem: context:          4704 bytes

INFO:  mem: http hdr rsvd:   34176 bytes ((1024 + 1112) x 16)

INFO:  mem: pollfd map:      38912

NOTICE:  mem: platform fd map: 38912 bytes

INFO:  LWS_MAX_EXTENSIONS_ACTIVE: 3

NOTICE:  mem: per-conn:          336 bytes + protocol rx buf

DEBUG: lws_allocate_header_table: wsi 0x2022650: ah 0x0

DEBUG: lws_allocate_header_table: wsi 0x2022650: ah 0x2916000: count 1 (on exit)

CLIENT: lws_client_connect: direct conn

CLIENT: lws_client_connect_2

CLIENT: lws_client_connect_2: address invalidurl.com

CLIENT: nonblocking connect retry

CLIENT: lws_client_connect_2

CLIENT: lws_client_connect_2: address invalidurl.com

CLIENT: connected

DEBUG: Server connection 0x2022650 (fd=15) dead

INFO: closing conn at LWS_CONNMODE...SERVER_REPLY

DEBUG: close: just_kill_connection: 0x2022650

INFO: remove_wsi_socket_from_fds: wsi=0x2022650, sock=15, fds pos=1

WebSocket (0x610000107e90) onConnectionError ...
DEBUG: Connection closed before server reply

WebSocket (0x610000107e90) onConnectionError ...
DEBUG: closing: shutdown ret 57

DEBUG: lws_free_header_table: wsi 0x2022650: ah 0x2916000 (count = 1)

Ready state is closing or was closed, code=2, quit websocket thread!
NOTICE: lws_context_destroy

WebSocket (0x610000107e90) onConnectionClosed ...
WebSocket thread exit, helper instance: 0x6100000b3500
JS: Error was fired
JS: Error was fired
JS: _wsiError websocket instance closed.
In the destructor of WebSocket (0x610000107e90)
```

**Comment by dumganhar** [comment]
And the following snippet is the client callback function i uses.
```
int WebSocket::onSocketCallback(struct lws *wsi,
                     int reason,
                     void *user, void *in, ssize_t len)
{
    //LOGD("socket callback for %d reason", reason);

    switch (reason)
    {
        case LWS_CALLBACK_DEL_POLL_FD:
        case LWS_CALLBACK_PROTOCOL_DESTROY:
        case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
            {
                if (reason == LWS_CALLBACK_CLIENT_CONNECTION_ERROR
                    || (reason == LWS_CALLBACK_PROTOCOL_DESTROY && _readyState == State::CONNECTING)
                    || (reason == LWS_CALLBACK_DEL_POLL_FD && _readyState == State::CONNECTING)
                    )
                {
                    onConnectionError();
                }
                else if (reason == LWS_CALLBACK_PROTOCOL_DESTROY && _readyState == State::CLOSING)
                {
                    onConnectionClosed();
                }
            }
            break;
```

**Comment by dumganhar** [comment]
I doubt my logic was wrong. Do i need to trigger `connection error` while reason is 
`LWS_CALLBACK_PROTOCOL_DESTROY` or `LWS_CALLBACK_DEL_POLL_FD` but the `readyState` is connecting ? Thanks

**Comment by lws-team** [comment]
No just wait a bit until i can study the two issues i identified.

**Comment by dumganhar** [comment]
OK, thanks a lot. :+1:

**Comment by lws-team** [comment]
OK I pushed a patch that solves the "excessive cleanup" problems, so it fails the connect normally on not understanding the redirect code.

**Comment by dumganhar** [comment]
Was the patch pushed?

**Comment by lws-team** [comment]
```
case LWS_CALLBACK_DEL_POLL_FD: 
case LWS_CALLBACK_PROTOCOL_DESTROY:
case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
```
These are three entirely different animals... I really doubt you want the first two to fall through to the handler for a connection error.

**Comment by lws-team** [comment]
Yeah is now.

**Comment by dumganhar** [comment]
Hi, @lws-team , i tested your patch. No assertion now.
But `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` was triggered twice. Could you find out what the problem is?

**Comment by lws-team** [comment]
Nope the test client gets that called once.

As I said you have a very weird fallthrough in the code you pasted.

You are aware you have to put

break;

after cases that should not fall through to the next case content?

**Comment by dumganhar** [comment]
```c++
int WebSocket::onSocketCallback(struct lws *wsi,
                     int reason,
                     void *user, void *in, ssize_t len)
{
    switch (reason)
    {
        case LWS_CALLBACK_CLIENT_ESTABLISHED:
            onConnectionOpened();
            break;

        case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
            onConnectionError();
            break;

        case LWS_CALLBACK_PROTOCOL_DESTROY:
        case LWS_CALLBACK_CLOSED:
            onConnectionClosed();
            break;

        case LWS_CALLBACK_CLIENT_RECEIVE:
            onClientReceivedData(in, len);
            break;

        case LWS_CALLBACK_CLIENT_WRITEABLE:
            onClientWritable();
            break;

        default:
            break;
    }
    return 0;
}
```
@lws-team , i changed the callback logic like above.
The twice `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` invocations have different stack frame.
Please refer to the following snapshot.

<img width="751" alt="screen shot 2016-01-13 at 22 17 51" src="https://cloud.githubusercontent.com/assets/493372/12296639/e7b14582-ba43-11e5-8bec-3e743ebd3f49.png">

The first was triggered by `lws_client_interpert_server_handshake`

<img width="726" alt="screen shot 2016-01-13 at 22 18 07" src="https://cloud.githubusercontent.com/assets/493372/12296642/eb7a5b22-ba43-11e5-94a5-d03d7815ce21.png">

The second error was triggered by `lws_close_free_wsi`.

How I handle error logic is:

When there is an error triggered, I will invoke `lws_context_destroy` to before exiting websocket thread.

Am i missing something or doing something wrong? Please help! Thanks.

**Comment by dumganhar** [comment]
@lws-team 

`libwebsocket-test-client` also trigger error twice, please refer to the following:

```bash
james@James-Chen bin$ ./libwebsockets-test-client ws://invalid.url.com
libwebsockets test client
(C) Copyright 2010-2015 Andy Green <andy@warmcat.com> licensed under LGPL2.1
[1452695630:5871] NOTICE: Initial logging level 7
[1452695630:5871] NOTICE: Libwebsockets version: 1.6.0 8308073
[1452695630:5871] NOTICE: IPV6 not compiled in
[1452695630:5871] NOTICE: libev support not compiled in
[1452695630:5872] NOTICE:  mem: platform fd map: 20480 bytes
[1452695630:5872] NOTICE:  mem: per-conn:          336 bytes + protocol rx buf
[1452695630:5872] NOTICE: dumb: connecting
[1452695630:5906] NOTICE: mirror: connecting
[1452695636:1128] ERR: dumb: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452695636:1130] NOTICE: dumb: connecting
[1452695637:1229] ERR: mirror: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452695637:1231] NOTICE: mirror: connecting
^C[1452695637:8584] ERR: Exiting
[1452695637:8584] NOTICE: lws_context_destroy
[1452695637:8584] ERR: dumb: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452695637:8585] ERR: mirror: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
```

**Comment by lws-team** [comment]
I tested it with invalid.url.com - before I replied yesterday about it - since that was what we had been talking about and you didn't mention any other condition.  I get one callback about CLIENT_ERROR.

And if you look closely at your log above, you also get ONE CLIENT_ERROR.  There are TWO connections in the test client, for dumb and mirror protocols.  You are just seeing each connection get the callback ONE time.

**Comment by dumganhar** [comment]
james@James-Chen bin$ ./libwebsockets-test-client ws://invalid.url.com
libwebsockets test client
(C) Copyright 2010-2015 Andy Green <andy@warmcat.com> licensed under LGPL2.1
[1452695630:5871] NOTICE: Initial logging level 7
[1452695630:5871] NOTICE: Libwebsockets version: 1.6.0 8308073
[1452695630:5871] NOTICE: IPV6 not compiled in
[1452695630:5871] NOTICE: libev support not compiled in
[1452695630:5872] NOTICE:  mem: platform fd map: 20480 bytes
[1452695630:5872] NOTICE:  mem: per-conn:          336 bytes + protocol rx buf
[1452695630:5872] NOTICE: dumb: connecting
[1452695630:5906] NOTICE: mirror: connecting
**[1452695636:1128] ERR: dumb: LWS_CALLBACK_CLIENT_CONNECTION_ERROR**  // The first time that the error was triggered
[1452695636:1130] NOTICE: dumb: connecting
[1452695637:1229] ERR: mirror: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
[1452695637:1231] NOTICE: mirror: connecting
**^C[1452695637:8584] ERR: Exiting**  // here i place Control+C, and lws_context_destroy
[1452695637:8584] NOTICE: lws_context_destroy
**[1452695637:8584] ERR: dumb: LWS_CALLBACK_CLIENT_CONNECTION_ERROR** // The second time that the error was triggered
[1452695637:8585] ERR: mirror: LWS_CALLBACK_CLIENT_CONNECTION_ERROR

@lws-team please refer to bold font. Thanks.

**Comment by lws-team** [comment]
Yeah... but the test client keeps retrying the connection.  Count the number of times it says "dumb: connecting" and "dumb: ...CONNECTION_ERROR".  In that case there is one error report per connection attempt as it should be.

However this is the same as the first problem, the "supporting documentation" to reproduce or understand the problem is wrong from your side, but the problem you have underneath is real.

I ignored not being able to reproduce it and went looking instead at how that could happen in the code and found a way.  I pushed a patch that should solve it.

**Comment by dumganhar** [comment]
@lws-team , it was fixed by using the latest patch. Thanks. :+1:
