### ISSUE TITLE
libuv backend

### ISSUE THREAD

**Issue by alexhultman** [warmcat/libwebsockets#411]
Hi guys.

I took a nap and then I implemented a quick test with libuv. It just started working but seems pretty stable. I need to add more functionalities (signals) and clean things up.

Would you be interested in working with me to add this new backend? It shares a lot with libev in terms of concepts so maybe it would be easiest to merge libev/libuv backends into one (with some differences, ofc). But this is completely up to you.

This is my (really ugly) first patch version:

```c
diff --git a/lib/context.c b/lib/context.c
index e4cbe78..20650cb 100644
--- a/lib/context.c
+++ b/lib/context.c
@@ -378,9 +378,10 @@ lws_context_destroy(struct lws_context *context)
 		}
 	}
 #ifdef LWS_USE_LIBEV
-	ev_io_stop(context->io_loop, &context->w_accept.watcher);
-	if (context->use_ev_sigint)
-		ev_signal_stop(context->io_loop, &context->w_sigint.watcher);
+    uv_poll_stop(&context->w_accept.watcher);
+    //ev_io_stop(context->io_loop, &context->w_accept.watcher);
+    //if (context->use_ev_sigint)
+        //ev_signal_stop(context->io_loop, &context->w_sigint.watcher);
 #endif /* LWS_USE_LIBEV */
 
 	for (n = 0; n < context->count_threads; n++) {
diff --git a/lib/libev.c b/lib/libev.c
index 167c045..a7fd1cb 100644
--- a/lib/libev.c
+++ b/lib/libev.c
@@ -30,24 +30,24 @@ void lws_feature_status_libev(struct lws_context_creation_info *info)
 }
 
 static void
-lws_accept_cb(struct ev_loop *loop, struct ev_io *watcher, int revents)
+lws_accept_cb(uv_poll_t *watcher, int status, int revents)
 {
 	struct lws_io_watcher *lws_io = container_of(watcher,
 						struct lws_io_watcher, watcher);
 	struct lws_context *context = lws_io->context;
 	struct lws_pollfd eventfd;
 
-	if (revents & EV_ERROR)
-		return;
+    if (status < 0/*revents & EV_ERROR*/)
+        return;
 
-	eventfd.fd = watcher->fd;
+    eventfd.fd = watcher->io_watcher.fd;
 	eventfd.events = 0;
-	eventfd.revents = EV_NONE;
-	if (revents & EV_READ) {
+    eventfd.revents = 0;//EV_NONE;
+    if (revents & UV_READABLE) {
 		eventfd.events |= LWS_POLLIN;
 		eventfd.revents |= LWS_POLLIN;
 	}
-	if (revents & EV_WRITE) {
+    if (revents & UV_WRITABLE) {
 		eventfd.events |= LWS_POLLOUT;
 		eventfd.revents |= LWS_POLLOUT;
 	}
@@ -55,9 +55,9 @@ lws_accept_cb(struct ev_loop *loop, struct ev_io *watcher, int revents)
 }
 
 LWS_VISIBLE void
-lws_sigint_cb(struct ev_loop *loop, struct ev_signal *watcher, int revents)
+lws_sigint_cb(uv_loop_t *loop, uv_signal_t *watcher, int revents)
 {
-	ev_break(loop, EVBREAK_ALL);
+    //ev_break(loop, EVBREAK_ALL);
 }
 
 LWS_VISIBLE int
@@ -74,17 +74,17 @@ lws_sigint_cfg(struct lws_context *context, int use_ev_sigint,
 }
 
 LWS_VISIBLE int
-lws_initloop(struct lws_context *context, struct ev_loop *loop)
+lws_initloop(struct lws_context *context, uv_loop_t *loop)
 {
-	struct ev_signal *w_sigint = &context->w_sigint.watcher;
-	struct ev_io *w_accept = &context->w_accept.watcher;
-	const char * backend_name;
+    //uv_signal_t *w_sigint = &context->w_sigint.watcher;
+    uv_poll_t *w_accept = &context->w_accept.watcher;
+    //const char * backend_name;
 	int status = 0;
-	int backend;
-	int m = 0; /* !!! TODO add pt support */
+    //int backend;
+    int m = 0; /* !!! TODO add pt support */
 
 	if (!loop)
-		loop = ev_default_loop(0);
+        loop = uv_default_loop();
 
 	context->io_loop = loop;
 
@@ -92,15 +92,17 @@ lws_initloop(struct lws_context *context, struct ev_loop *loop)
 	 * Initialize the accept w_accept with the listening socket
 	 * and register a callback for read operations
 	 */
-	ev_io_init(w_accept, lws_accept_cb, context->pt[m].lserv_fd, EV_READ);
-	ev_io_start(context->io_loop,w_accept);
+    uv_poll_init(context->io_loop, w_accept, context->pt[m].lserv_fd);
+    uv_poll_start(w_accept, UV_READABLE, lws_accept_cb);
+    //ev_io_init(w_accept, lws_accept_cb, context->pt[m].lserv_fd, UV_READABLE);
+    //ev_io_start(context->io_loop,w_accept);
 
 	/* Register the signal watcher unless the user says not to */
 	if (context->use_ev_sigint) {
-		ev_signal_init(w_sigint, context->lws_ev_sigint_cb, SIGINT);
-		ev_signal_start(context->io_loop,w_sigint);
+        //ev_signal_init(w_sigint, context->lws_ev_sigint_cb, SIGINT);
+        //ev_signal_start(context->io_loop,w_sigint);
 	}
-	backend = ev_backend(loop);
+    /*backend = ev_backend(loop);
 
 	switch (backend) {
 	case EVBACKEND_SELECT:
@@ -126,7 +128,7 @@ lws_initloop(struct lws_context *context, struct ev_loop *loop)
 		break;
 	}
 
-	lwsl_notice(" libev backend: %s\n", backend_name);
+    lwsl_notice(" libev backend: %s\n", backend_name);*/
 
 	return status;
 }
@@ -135,22 +137,24 @@ LWS_VISIBLE void
 lws_libev_accept(struct lws *new_wsi, int accept_fd)
 {
 	struct lws_context *context = lws_get_context(new_wsi);
-	struct ev_io *r = &new_wsi->w_read.watcher;
-	struct ev_io *w = &new_wsi->w_write.watcher;
+    uv_poll_t *r = &new_wsi->w_read.watcher;
+    //uv_poll_t *w = &new_wsi->w_write.watcher;
 
 	if (!LWS_LIBEV_ENABLED(context))
 		return;
 
 	new_wsi->w_read.context = context;
 	new_wsi->w_write.context = context;
-	ev_io_init(r, lws_accept_cb, accept_fd, EV_READ);
-	ev_io_init(w, lws_accept_cb, accept_fd, EV_WRITE);
+    uv_poll_init(context->io_loop, r, accept_fd);
+    //ev_io_init(r, lws_accept_cb, accept_fd, UV_READABLE);
+    //ev_io_init(w, lws_accept_cb, accept_fd, UV_WRITABLE);
 }
 
 LWS_VISIBLE void
 lws_libev_io(struct lws *wsi, int flags)
 {
 	struct lws_context *context = lws_get_context(wsi);
+    int current_events = wsi->w_read.watcher.io_watcher.pevents & (UV_READABLE | UV_WRITABLE);
 
 	if (!LWS_LIBEV_ENABLED(context))
 		return;
@@ -162,15 +166,26 @@ lws_libev_io(struct lws *wsi, int flags)
 	       (flags & (LWS_EV_READ | LWS_EV_WRITE)));
 
 	if (flags & LWS_EV_START) {
-		if (flags & LWS_EV_WRITE)
-			ev_io_start(context->io_loop, &wsi->w_write.watcher);
-		if (flags & LWS_EV_READ)
-			ev_io_start(context->io_loop, &wsi->w_read.watcher);
+        if (flags & LWS_EV_WRITE)
+            current_events |= UV_WRITABLE;
+            //ev_io_start(context->io_loop, &wsi->w_write.watcher);
+        if (flags & LWS_EV_READ)
+            current_events |= UV_READABLE;
+            //ev_io_start(context->io_loop, &wsi->w_read.watcher);
+
+        uv_poll_start(&wsi->w_read.watcher, current_events, lws_accept_cb);
 	} else {
-		if (flags & LWS_EV_WRITE)
-			ev_io_stop(context->io_loop, &wsi->w_write.watcher);
-		if (flags & LWS_EV_READ)
-			ev_io_stop(context->io_loop, &wsi->w_read.watcher);
+        if (flags & LWS_EV_WRITE)
+            current_events &= ~UV_WRITABLE;
+            //ev_io_stop(context->io_loop, &wsi->w_write.watcher);
+        if (flags & LWS_EV_READ)
+            current_events &= ~UV_READABLE;
+            //ev_io_stop(context->io_loop, &wsi->w_read.watcher);
+
+        if (!(current_events & (UV_READABLE | UV_WRITABLE)))
+            uv_poll_stop(&wsi->w_read.watcher);
+        else
+            uv_poll_start(&wsi->w_read.watcher, current_events, lws_accept_cb);
 	}
 }
 
@@ -190,5 +205,5 @@ LWS_VISIBLE void
 lws_libev_run(const struct lws_context *context)
 {
 	if (context->io_loop && LWS_LIBEV_ENABLED(context))
-		ev_run(context->io_loop, 0);
+        uv_run(context->io_loop, 0);
 }
diff --git a/lib/libwebsockets.h b/lib/libwebsockets.h
index 9b66352..400ab81 100644
--- a/lib/libwebsockets.h
+++ b/lib/libwebsockets.h
@@ -166,7 +166,7 @@ struct sockaddr_in;
 #endif
 
 #ifdef LWS_USE_LIBEV
-#include <ev.h>
+#include <uv.h>
 #endif /* LWS_USE_LIBEV */
 
 #ifndef LWS_EXTERN
@@ -1453,17 +1453,17 @@ LWS_VISIBLE LWS_EXTERN int LWS_WARN_UNUSED_RESULT
 lws_http_transaction_completed(struct lws *wsi);
 
 #ifdef LWS_USE_LIBEV
-typedef void (lws_ev_signal_cb)(EV_P_ struct ev_signal *w, int revents);
+typedef void (lws_ev_signal_cb)(uv_loop_t *l, uv_signal_t *w, int revents);
 
 LWS_VISIBLE LWS_EXTERN int
 lws_sigint_cfg(struct lws_context *context, int use_ev_sigint,
 	       lws_ev_signal_cb *cb);
 
 LWS_VISIBLE LWS_EXTERN int
-lws_initloop(struct lws_context *context, struct ev_loop *loop);
+lws_initloop(struct lws_context *context, uv_loop_t *loop);
 
 LWS_VISIBLE void
-lws_sigint_cb(struct ev_loop *loop, struct ev_signal *watcher, int revents);
+lws_sigint_cb(uv_loop_t *loop, uv_signal_t *watcher, int revents);
 #endif /* LWS_USE_LIBEV */
 
 LWS_VISIBLE LWS_EXTERN int
diff --git a/lib/private-libwebsockets.h b/lib/private-libwebsockets.h
index 72f71b4..d20da12 100644
--- a/lib/private-libwebsockets.h
+++ b/lib/private-libwebsockets.h
@@ -117,7 +117,7 @@
 #include <arpa/inet.h>
 #include <poll.h>
 #ifdef LWS_USE_LIBEV
-#include <ev.h>
+#include <uv.h>
 #endif /* LWS_USE_LIBEV */
 #include <sys/mman.h>
 
@@ -439,12 +439,12 @@ struct lws;
 
 #ifdef LWS_USE_LIBEV
 struct lws_io_watcher {
-	struct ev_io watcher;
+    uv_poll_t watcher;
 	struct lws_context* context;
 };
 
 struct lws_signal_watcher {
-	struct ev_signal watcher;
+    uv_signal_t watcher;
 	struct lws_context* context;
 };
 #endif /* LWS_USE_LIBEV */
@@ -560,7 +560,7 @@ struct lws_context {
 	struct lws **lws_lookup;  /* fd to wsi */
 #endif
 #ifdef LWS_USE_LIBEV
-	struct ev_loop* io_loop;
+    uv_loop_t *io_loop;
 	struct lws_io_watcher w_accept;
 	struct lws_signal_watcher w_sigint;
 	lws_ev_signal_cb* lws_ev_sigint_cb;
```

**Comment by JoakimSoderberg** [comment]
Just as a note on patches. I would recommend you create a Pull Request instead, a lot easier for others to get it then...

**Comment by lws-team** [comment]
Yes I'm interested to integrate it... this 'hacking it in' is great as a first step thanks since I can do that then without particularly understanding libuv.  I'll look at it tonight (ie, +12h).  As Joakim says pushing it somewhere is easiest but I can probably screenscrape it.

We need to offer a build that can support both ev and uv, selectable at context creation time, for distro build case.  But I can do the plumbing to translate the patch into that myself.

Something else that needs to happen to both ev and uv is move the io_loop out of the context and into the new per_thread (pt) context struct.  It means you can spawn n service threads and each runs his own event loop and [e]poll() and services his own subset of fds simultaneously.  The builtin poll() stuff already supports this, I'll do ev/uv at the same time.

**Comment by alexhultman** [comment]
So maybe I should focus on providing uv.c together with the needed stuff under LWS_USE_LIBUV ifdefs, just like libev is implemented? Then you can do the CMake plumbing and the needed changes to both ev and uv? I ran this under valgrind and it seems to have 1 invalid write error which I'll be taking a look at later. Otherwise it seems stable(ish?).

**Comment by lws-team** [comment]
I get some time waiting for builds and started looking at that already.

I'll push something in a bit to test.

**Comment by lws-team** [comment]
Okay please try branch 'libuv-test'.  You need cmake -DLWS_WITH_LIBUV=1

This has the libuv stuff integrated, and it works as before for libev.

I added a test-server-libuv by copying the libev one, but I did not attempt to convert it since I don't know libev.  If you also enable cmake -D LWS_WITH_LIBEV=1 then he can build, but he won't work right.  Without libev enabled, he breaks build.  It would be great if after fixing / confirming the libuv support with your app, you could visit the libuv test app and convert him from libev to libuv.

The per-thread conversion is also done for both but only tested on one service thread for libev.  Something probably needs to be done now to destroy the lib_v service loops in context_destroy but I dunno what.

**Comment by alexhultman** [comment]
I saw the commits and this is very nice, you even fixed my bad formatting :) This is perfect, I will finish the implementation soon.

**Comment by lws-team** [comment]
I rebased libuv-test branch on current master and added some small patches on top.  The first two patches are unchanged from what I pushed before.  The additional patches -->

1) move all the additional lib[u|v] start/stop handling directly into the change_pollfd code and get rid of the copied code everywhere.  That probably solves some corner cases where some change_pollfd()s did not have the liv[u|v] code copied after them

2) little update on the test-server-libuv skeleton (really, when I left it, a cut-and-paste of libev test with a couple of edits) to align with api deprecation in master

3) fix a bug in context_destroy if libuv support built, he should only attempt to cleanup libuv things if libuv was enabled at runtime as well, same for libev

You should be able to fetch this branch to a local temp branch

```
git fetch https://github.com/warmcat/libwebsockets.git +libuv-test:temp
```

switch to your local "temp" branch and then git cherry-pick your existing patches on top. (Apologies if you know how to do already).

Hopefully we won't have to keep doing this for too long.

**Comment by alexhultman** [comment]
Yes I will be finishing this up in the nearest time. I haven't done anything since the first patch so I will be doing a burst sometime soon.

**Comment by alexhultman** [comment]
I'm working on updating my wrapper to the libuv-test branch and it is stable until I disconnect, then it crashes in _lws_change_pollfd -> it seems to call uv_poll_start, I think it should call uv_poll_stop. Disconnection worked before so this might be some small change in _lws_change_pollfd that made this?

**Comment by alexhultman** [comment]
Yes, I enabled debug build (*facepalm*) and it crashes in lws_libuv_io on disconnection due to flags being 5, which is LWS_EV_START so it calls uv_poll_start. I think lws_libuv_io should be called so that LWS_EV_STOP check pases (runs uv_poll_stop).

**Comment by alexhultman** [comment]
If you want to see what I'm doing you can clone node-lws and (if you have QtCreator) open src/lws.pro to get a test server which can use libev and libuv depending on if you set LIBUV_BACKEND or not. The libev backend does not crash but I'm not really doing anything wrong (as far as I cal tell) because I get called to start a poll for reading and that is what I do.

You can see what build options I use in the README.md.

**Comment by alexhultman** [comment]
AH! LOL!

**Comment by alexhultman** [comment]
I cleaned up some comments, basically it crashes when I disconnect. I need to look at this.

**Comment by alexhultman** [comment]
Yes so I cannot find anything right now. It did handle disconnections before (in the original patch) but now it is broken. I don't know what has happened. uv_poll_start gets called with fd=0 (the accept socket is fd = 4 since we have 3 standard streams) so it does not get the correct fd. wsi->sock is correct but I think the watcher has been invalidated somehow, reset in some way.

**Comment by lws-team** [comment]
If you can update the llibuv test app and push somewhere so I can reproduce, I can also help debug.

**Comment by lws-team** [comment]
Btw if node or your app closes stdin, which is fd 0, fd0 will get recycled and is a legit fd.  Explicit bad fd number is -1.  Or it can be showing up some other bug now we moved lib*v start / stop handling to the generic change_pollfd().

**Comment by alexhultman** [comment]
All standard files (stdin and company) are still opened and the passed wsi->sock is a fd higher than 3, it is only the passed watcher which holds the fd = 0, so it has changed from its uv_poll_init (fd are set on init of the watcher). So somewhere the watcher gets "invalidated". I did a test to see if fd is reset to 0 when I call uv_poll_stop but it was still set and the documentation does not hint that is is wrong to restart a stopped watcher.

**Comment by alexhultman** [comment]
Yes I will finish the test-server so that you can reproduce.

**Comment by alexhultman** [comment]
Hi

Did you manage to fix the problems with the disconnection? Do you have anything to share?

**Comment by lws-team** [comment]
Right now I am in sunny vietnam, I have some time but in small chunks.  Both the libuv and this http keeplive problem need a big chunk of time all at once, that may not happen until Sunday.

**Comment by alexhultman** [comment]
Well have a nice time then. I'm not in a hurry.

**Comment by lws-team** [comment]
This now works well enough to do the libuv test server correctly with Chrome and the test client attached, so I think it should act well if node.js usage is broadly similar.

I also checked it builds OK without libuv enabled in cmake.  It's pushed on master, please look at the bottom of the libuv test server source to see what happened and give it a try.

**Comment by lws-team** [comment]
I just updated that last patch, valgrind revealed libuv needed much more integration on the fd close part than libev does.  It's solved with one small valgrind issue left I am not sure what we are doing wrong.

**Comment by alexhultman** [comment]
I just came home. Will test the uv support.

The Valgrind issue is about me not closing the loop resources correctly in the test server:

-	ev_loop_destroy(loop);
 +	uv_stop(loop);

It should be

uv_stop(loop);
uv_loop_close(loop);

**Comment by alexhultman** [comment]
I have updated the wrapper and run a lot of stress tests and Valgrind runs. It is rock solid but yes at exit there is something wrong.

One thing that is strange is that you never seem to call lws_libuv_destroyloop, and you call the (now required) signal callback even though I set it to unused in lws_uv_sigint_cfg.

**Comment by lws-team** [comment]
Great about it being reasonably solid.

lws_libuv_destroyloop() is called from lws_context_destroy(), if you're getting to destroy the context in the test app it should call through to it.

One complication compared to libev is that we must continue libuv service after we want to exit, so that it may close all of its 'handles' asynchronously.

Because of that with libuv,

1)  lws_libuv_stop() is used in user code to start closing everything

2) only when he sees the number of wsi has gotten to 0 does he

3) call lws_libuv_kill() to actually stop the libev event loop.

4) That should break us out of the top level test app service action and do the lws_context_destroy(), which shouldn't need service any more.

It may be relevant because I only found that was needed by seeing similar weird things from valgrind about internal libuv api allocations being left alive.  So it may be telling us some other close or destroy action for libuv is required and perhaps requires service to complete.

At any rate from what I saw, it was one 128 or 256 byte allocation left alive from the whole session.  I would like to clean it out if I could understand it, but that's not so terrible as valgrind problems go.

**Comment by alexhultman** [comment]
Ah, I missed the lws_context_destroy. You actually did a lot of changes and made a lot of fixes that I just missed totally.

The Valgrind issue is essentially a non-issue but I understand you wanting to fix it - there should be no issues left when we are done. I will take some time to look at this, it should be simple to fix because it is so easy to reproduce.

**Comment by alexhultman** [comment]
This is one Valgrind dump from the wrapper:

```
[alexhultman@localhost ~]$ valgrind node main
==2154== Memcheck, a memory error detector
==2154== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==2154== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==2154== Command: node main
==2154== 
==2154== Warning: set address range perms: large range [0x34eeed84b000, 0x34ef0d84b000) (noaccess)
Running server on port 3000
[Connection]
[Message: Rock it with HTML5 WebSocket]
[Message: Rock it with HTML5 WebSocket]
[Message: Rock it with HTML5 WebSocket]
[Message: Rock it with HTML5 WebSocket]
[Message: Rock it with HTML5 WebSocket]
[Message: Rock it with HTML5 WebSocket]
[Close]
persistent per socket data
[Connection]
[Close]
persistent per socket data
[Connection]
[Message: Rock it with HTML5 WebSocket]
[Message: Rock it with HTML5 WebSocket]
[Message: Rock it with HTML5 WebSocket]
[Close]
persistent per socket data
^C==2154== 
==2154== HEAP SUMMARY:
==2154==     in use at exit: 24,766,164 bytes in 3,580 blocks
==2154==   total heap usage: 22,842 allocs, 19,262 frees, 74,025,029 bytes allocated
==2154== 
==2154== LEAK SUMMARY:
==2154==    definitely lost: 0 bytes in 0 blocks
==2154==    indirectly lost: 0 bytes in 0 blocks
==2154==      possibly lost: 4,176 bytes in 23 blocks
==2154==    still reachable: 24,761,988 bytes in 3,557 blocks
==2154==         suppressed: 0 bytes in 0 blocks
==2154== Rerun with --leak-check=full to see details of leaked memory
==2154== 
==2154== For counts of detected and suppressed errors, rerun with: -v
==2154== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

It seems clear. I'm not using the signal feature. I haven't looked any further yet, but I'll take some time soon to look at this.

**Comment by alexhultman** [comment]
Ah I see. The reason I get a "clean" dump is because I do not shut down the loop correctly, I just exit(0) currently. So there is no registered memory leak because things are still reachable. So it is not really that clean.

**Comment by lws-team** [comment]
It's usually a safe bet that if the test app version has a problem, everything else is going to have the same problem or worse.  The test apps have the "current best practice" for using the library generally (including coordinating the exit in libuv case).

**Comment by alexhultman** [comment]
Yes I have a tendency to speak before I have finished my thoughts. It happened again lol.

**Comment by alexhultman** [comment]
There is a problem where lws_libuv_destroyloop gets called before lws_uv_initloop has been called. This happens if the server cannot start listening on the port. Then it will destroy the context which will call this function.

Maybe we should set the io_loop_uv to NULL on lws_create_context and only call lws_libuv_destroyloop if the loop is not NULL?

**Comment by alexhultman** [comment]
Sorry for patch but this little thing fixes it (you already clear the context memory with lws_zalloc):

```
diff --git a/lib/libuv.c b/lib/libuv.c
index e3d68c6..461dc3e 100644
--- a/lib/libuv.c
+++ b/lib/libuv.c
@@ -124,6 +124,9 @@ lws_libuv_destroyloop(struct lws_context *context, int tsi)
        if (!(context->options & LWS_SERVER_OPTION_LIBUV))
                return;
 
+       if (!pt->io_loop_uv)
+               return;
+
        if (context->use_ev_sigint)
                uv_signal_stop(&pt->w_sigint.uv_watcher);
        for (m = 0; m < ARRAY_SIZE(sigs); m++)
```

**Comment by alexhultman** [comment]
This also applies to ev. I will create a pull request for both uv and ev.

**Comment by alexhultman** [comment]
Did you notice that uv_loop_close returns UV_EBUSY in lws_libuv_destroyloop?

```
int uv_loop_close(uv_loop_t* loop)
Closes all internal loop resources.
This function must only be called once the loop has finished its execution or it will return UV_EBUSY. [...]
```
That could explain the leak, the loop doesn't seem to close properly.

**Comment by lws-team** [comment]
Sounds like it's related... but I dunno how to sync the destroy better.  We do it after the last wsi's libuv 'close handle' callback appears atm.  I don't know any other event after that to hang the destroy call off of.  But I have little idea about libuv maybe there's an obvious way.

**Comment by alexhultman** [comment]
The best way is probably something like just calling uv_stop(loop) which will then cause uv_run to return and then *after* this return then you do the uv_loop_close.

https://nikhilm.github.io/uvbook/eventloops.html

They state that uv_stop will not "kill" the loop but just schedule a stop so the loop is only guaranteed to be stopped when uv_run returns and uv_loop_alive(loop) is false.

**Comment by lws-team** [comment]
We do have uv_stop() in the flow, but maybe it's misused somehow..

The main thing missing is an event or place in the code we reach after he asynchrously is ready to close.  If we have that (and we're on the right track) just moving the destroy there should solve it.

**Comment by alexhultman** [comment]
Yes the "event" of a stop is when uv_run is no longer blocking. So it is up to the user to destroy the context. Maybe it is as simple as changing uv_loop_close with uv_stop and then adding uv_loop_close to lws_context_destroy?

**Comment by alexhultman** [comment]
So it turned out you already did what I was talking about but it seems there are some open handles still left. We can debug what handles are still left open if we want to but this latest fix closes the loop gracefully at least.

**Comment by lws-team** [comment]
I think the libuv gods probably know another way, but this looks fine to me.  It nails it and we know by that the issue was around at least one extra logical handle lying around.

I'll close this issue now but if there's anything more we should discuss about libuv or helping your node.js project please feel free to reopen or make a new issue.

**Comment by alexhultman** [comment]
Yes thanks for the cooperation, we can iterate on this in the future.

**Comment by meiry** [comment]
Hey , is there any short tutorial on how to use libwebsockets and libuv?

**Comment by lws-team** [comment]
Have you looked at test-server/test-server-libuv?
https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-libuv.c

**Comment by meiry** [comment]
Hey , i trying to figure out how to compile this test , 
managed to compile only those :
![websockets](https://cloud.githubusercontent.com/assets/1107316/14142890/021d632c-f691-11e5-8394-9495096b2daa.png)

**Comment by lws-team** [comment]
Give cmake -DLWS_WITH_LIBUV=1

Make sure you have libuv and libuv-dev (or -devel) packages installed as well.

**Comment by JoakimSoderberg** [comment]
Of course first you need to turn on libuv support in cmake, before you can use libws with libuv...

To do that you follow the compiling guide, but also set the `LWS_WITH_LIBUV` cmake option. This will generate the visual studio project correctly.

Since you are using windows. The search script will most likely not automatically find the libuv libs on your system. So you will also need to supply the paths for that using `LWS_LIBUV_LIBRARIES` (path to where uv.lib can be found) and `LWS_LIBUV_INCLUDE_DIRS` (path to where uv.h can be found)

```bash
cmake -DLWS_WITH_LIBUV=ON -DLWS_LIBUV_LIBRARIES="<path to libuv libs dir>" -DLWS_LIBUV_INCLUDE_DIRS="<path to libuv include dir>"  ..
```

**Comment by JoakimSoderberg** [comment]
@lws-team He's using Windows, so those packages won't help ;)

**Comment by lws-team** [comment]
Oh... I am too pure to recognize that from the screenshot ;-)  Then good job you're here to advise.

**Comment by meiry** [comment]
Well  i see my mistake i configure the CMAKE via the gui tool 
then i need to run manually 
```cmake -DLWS_WITH_LIBUV=ON 

right?

**Comment by JoakimSoderberg** [comment]
as I said you can do via the commandline... But all those options should be available via the gui tool as well... Via command line to list all options it is:

```
cmake -L ..
```

After running configure in the gui you get the options:

![2016-03-30 15_45_14-cmake 3 5 0 - c__users_js_dev_libwebsockets_build](https://cloud.githubusercontent.com/assets/1446626/14144055/8091f702-f68e-11e5-9daa-62de7a46146e.png)

But yes, I would recommend using the command line :)

**Comment by meiry** [comment]
ok via the cmake GUI i added :  
LWS_USE_LIBUV = 1
LWS_WITH_LIBUV=1
![websockets2](https://cloud.githubusercontent.com/assets/1107316/14144091/136e011c-f697-11e5-821a-7e95d833ec6a.png)

hit Configure + generate 

Then in VS 2013 i compile the websockets lib 
and it gives me the error that say it can't find the :  
``` #include <uv.h>

and when i check the incluede paths i dont see the libuv path i added . 
![websockets3](https://cloud.githubusercontent.com/assets/1107316/14144241/89d00620-f697-11e5-9a00-453772b082f8.png)

**Comment by JoakimSoderberg** [comment]
Might help if you enter hte path with `/` and not `\` this is how cmake internally stores them... and also, close VS during genrating the project

**Comment by meiry** [comment]
about the path as you can see i entered the zlib path manually and it worked fine .
i think cmake Smart enough to deal with the "/" "\"

**Comment by lws-team** [comment]
Only on master, there's an "accidental paste"[1] bug in the CMakeLists.txt file

```
set(LWS_LIBUV_LIBRARIES CACHE PATH "Path to the libuv library")
set(LWS_LIBUVLWS_LIBEV_LIBRARIES_INCLUDE_DIRS CACHE PATH "Path to the libuv include directory")
```

I just pushed a patch fixing it, that should solve this.

[1] I do all my work on a tablet over VNC to a build machine.  That works perfectly except I can't find any BT mouse or trackpad that won't make the tablet believe it has received a "gesture" periodically.

**Comment by lws-team** [comment]
Btw talking of vs + linux

https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/

in addition to this linux syscall subsystem they added to run linux apps on win10 natively...

**Comment by meiry** [comment]
Still the fix does not add the test-server-libuv.c to the project 
i git clone the project , 
verifyed your fixed are there 
configured cmake via cmake gui 
![cmake_gui](https://cloud.githubusercontent.com/assets/1107316/14167301/eac0fb3e-f722-11e5-92c7-2fd556b5e137.png)


but still it doesn't load into VS 
![vs_none_libuv](https://cloud.githubusercontent.com/assets/1107316/14167311/f8464d54-f722-11e5-9efa-a61d5e04ecd8.png)

**Comment by lws-team** [comment]
You should tell CMake "LWS_WITH_UV=1"

LWS_USE_UV is set by CMakeLists.txt itself and exported in lws_config.h

**Comment by meiry** [comment]
I did it is with 1 
![with1](https://cloud.githubusercontent.com/assets/1107316/14167440/0b279256-f724-11e5-9df2-bfa162833c48.png)

**Comment by lws-team** [comment]
When you run cmake from the commandline, he dumps his feeling at the end of the script so we can see what he understood, not just what we set.

```
/usr/bin/cmake -H/projects/libwebsockets -B/projects/libwebsockets/build --check-build-system CMakeFiles/Makefile.cmake 0
Re-run cmake file: Makefile older than: ../libwebsockets.spec
-- CMAKE_TOOLCHAIN_FILE=''
Git commit hash: agreen@build.warmcat.com-v1.7.0-94-ge720910
zlib include dirs: /usr/include
zlib libraries: /lib64/libz.so
Compiling with SSL support
POLARSSL include dir: /usr/include
POLARSSL libraries: /usr/lib64/libmbedtls.so.9
libev include dir: /usr/include
libev libraries: /lib64/libev.so
libuv include dir: /usr/include
libuv libraries: /lib64/libuv.so
Generating SSL Certificates for the test-server...
SUCCESSFULLY generated SSL certificate
Generating API documentation
-- Looking for RPMTools... - found rpmuild is /bin/rpmbuild
-- RPMTools:: Using RPM_ROOTDIR=/projects/libwebsockets/build/RPM
-- Simple copy spec file <libwebsockets.spec> --> </projects/libwebsockets/build/RPM/SPECS/libwebsockets.spec>
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = ON (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_USE_POLARSSL = 1 (PolarSSL replacement for OpenSSL)
 LWS_USE_MBEDTLS = OFF (mbedtls (nee Polarssl) replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = 1
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_ECHO = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_USE_LIBEV = 1
 LWS_USE_LIBUV = 1    <<<<=====
 LWS_IPV6 = OFF
 LWS_WITH_HTTP2 = 0
 LWS_MBED3 = OFF
 LWS_SSL_SERVER_WITH_ECDH_CERT = 1
 LWS_MAX_SMP = 32
 LWS_WITH_CGI = 1
 LWS_HAVE_OPENSSL_ECDH_H = 1
 LWS_WITH_HTTP_PROXY = 0
 LIBHUBBUB_LIBRARIES = /lib64/libhubbub.so
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/libwebsockets/build
```

can you get that output?

**Comment by meiry** [comment]
yes 
```
CMAKE_TOOLCHAIN_FILE=''
Git commit hash: dm-imcs\meiry@Meiry-win7-v1.7.0-92-g02ff145
CMake Warning (dev) at CMakeLists.txt:698 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "zlib_internal".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

zlib include dirs: win32port/zlib
zlib libraries: G:/dev/cpp/servers/libuv/libwebsockets_git/libwebsockets/build/lib/$(Configuration)/zlib_internal.lib
libuv include dir: g:\dev\cpp\servers\libuv\git\libuv\include\
libuv libraries: g:\dev\cpp\servers\libuv\git\libuv\Debug\lib\
RPM tools not available on Win32 systems
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = OFF (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_USE_POLARSSL = OFF (PolarSSL replacement for OpenSSL)
 LWS_USE_MBEDTLS = OFF (mbedtls (nee Polarssl) replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_ECHO = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_USE_LIBEV = 
 LWS_USE_LIBUV = 1   <<<<<<<<<<<<<<===============HERE IT IS <<<<<<<<<<<<<<<<<<<
 LWS_IPV6 = OFF
 LWS_WITH_HTTP2 = OFF
 LWS_MBED3 = ON
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 1
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H = 
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES = 
---------------------------------------------------------------------
Configuring done
WARNING: Target "test-server-extpoll" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server-extpoll" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server-extpoll" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server-extpoll" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets_shared" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets_shared" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets_shared" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets_shared" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "lwsws" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "lwsws" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "lwsws" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "lwsws" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-echo" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-echo" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-echo" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-echo" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-ping" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-ping" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-ping" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-ping" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-fraggle" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-fraggle" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-fraggle" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-fraggle" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-client" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-client" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-client" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-client" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets_shared" requests linking to directory "g:\dev\cpp\servers\libuv\git\libuv\Debug\lib".  Targets may link only to libraries.  CMake is dropping the item.
Generating done
```

**Comment by meiry** [comment]
How does the command line for cmake that you are using ?

**Comment by lws-team** [comment]
Just 

```
$ mkdir build
$ cd build
$ cmake .. -DLWS_WITH_LIBUV=1
```

is enough.  Let me check if anything disables libuv on windows in the CMakeLists.txt

**Comment by lws-team** [comment]
Hm the problem is it's only built for unix

```
			if (UNIX AND NOT ((CMAKE_C_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
				AND LWS_WITH_LIBUV)
```

tbh I didn't know it was available for windows.

Please try remove the UNIX AND from line 968 above.

**Comment by meiry** [comment]
Now it does create the uv project in VS but when compiling i got banch of compilation errors 
Im using the latest libuv code 
```
 3>  libuv.c
4>  libuv.c
3>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(36): warning C4013: 'container_of' undefined; assuming extern returning int
3>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(37): error C2059: syntax error : 'type'
3>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(41): error C2039: 'io_watcher' : is not a member of 'uv_poll_s'
3>          g:\dev\cpp\servers\libuv\git\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
3>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(92): error C2059: syntax error : 'type'
3>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(191): warning C4028: formal parameter 2 different from declaration
3>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(210): error C2039: 'io_watcher' : is not a member of 'uv_poll_s'
3>          g:\dev\cpp\servers\libuv\git\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
3>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(333): error C2036: 'void *' : unknown size
3>  Generating Code...
4>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(36): warning C4013: 'container_of' undefined; assuming extern returning int
4>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(37): error C2059: syntax error : 'type'
4>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(41): error C2039: 'io_watcher' : is not a member of 'uv_poll_s'
4>          g:\dev\cpp\servers\libuv\git\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
4>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(92): error C2059: syntax error : 'type'
4>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(191): warning C4028: formal parameter 2 different from declaration
4>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(210): error C2039: 'io_watcher' : is not a member of 'uv_poll_s'
4>          g:\dev\cpp\servers\libuv\git\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
4>G:\dev\cpp\servers\libuv\libwebsockets_git\libwebsockets\lib\libuv.c(333): error C2036: 'void *' : unknown size

**Comment by lws-team** [comment]
I can fix or attempt to fix most of them, but the line 41 problem is because the only hiits for io_watcher are in a unix specific platform support file in uv

```
/usr/include/uv-unix.h:  uv__io_t io_watcher;
```

**Comment by lws-team** [comment]
Hum it looks like the whole using io_watcher thing is misguided

```
#define UV_POLL_PRIVATE_FIELDS                                                \
  uv__io_t io_watcher;
```

the corresponding windows definition is different

```
#define UV_POLL_PRIVATE_FIELDS                                                \
  SOCKET socket;                                                              \
  /* Used in fast mode */                                                     \
  SOCKET peer_socket;                                                         \
  AFD_POLL_INFO afd_poll_info_1;                                              \
  AFD_POLL_INFO afd_poll_info_2;                                              \
  /* Used in fast and slow mode. */                                           \
  uv_req_t poll_req_1;                                                        \
  uv_req_t poll_req_2;                                                        \
  unsigned char submitted_events_1;                                           \
  unsigned char submitted_events_2;                                           \
  unsigned char mask_events_1;                                                \
  unsigned char mask_events_2;                                                \
  unsigned char events;
```

@alexhultman  does windows + libuv matter to you?  It looks like stuff related to io_watcher in poll at least needs redoing somehow.

**Comment by lws-team** [comment]
It seems Alex is busy with his own thing.

I pushed a patch that should help with some or all of the issues.

https://github.com/warmcat/libwebsockets/commit/e42c2a9de72fb57a096b188fe0df1936044932bd

**Comment by alexhultman** [comment]
Sorry I didn't think there were any issues so I just ignored the notifications. If it doesn't work for Windows that is ofc bad and should be fixed.

**Comment by alexhultman** [comment]
There is an uv_fileno function to get the platform dependent "socket type" but I don't have Windows so I cannot test it.

**Comment by alexhultman** [comment]
I did manage to find a person to port my stuff to Windows so I can share any information we find when that happens.

**Comment by meiry** [comment]
Ok thanks for your fast response , please update this thread so i can get notification in my email

**Comment by lws-team** [comment]
The next move is for you, Meiry, to test the patch I pushed.  The only guy here who both has windows, so he can test it, and cares about lws + libuv working there is yourself.

**Comment by meiry** [comment]
Sure Thanks! 
unfortunately i can test it only on Sunday morning .

**Comment by meiry** [comment]
Hey i was testing it , still have compilation errors : 
1. 
```
4>  libuv.c
3>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\lib\libuv.c(42): error C2039: 'sock' : is not a member of 'uv_poll_s'
3>          d:\dev\cpp\game_servers\libuv\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
3>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\lib\libuv.c(195): warning C4028: formal parameter 2 different from declaration
3>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\lib\libuv.c(215): error C2039: 'io' : is not a member of 'uv_poll_s'
3>          d:\dev\cpp\game_servers\libuv\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
3>  Generating Code...
4>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\lib\libuv.c(42): error C2039: 'sock' : is not a member of 'uv_poll_s'
4>          d:\dev\cpp\game_servers\libuv\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
4>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\lib\libuv.c(195): warning C4028: formal parameter 2 different from declaration
4>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\lib\libuv.c(215): error C2039: 'io' : is not a member of 'uv_poll_s'
4>          d:\dev\cpp\game_servers\libuv\libuv\include\uv.h(710) : see declaration of 'uv_poll_s'
4>  Generating Code...
5>------ Build started: Project: lwsws, Configuration: Debug Win32 ------
5>  Building Custom Rule d:/dev/cpp/game_servers/libwebsockets/libwebsockets/CMakeLists.txt
5>  CMake does not need to re-run because d:\dev\cpp\game_servers\libwebsockets\libwebsockets\build\CMakeFiles\generate.stamp is up-to-date.
```


 

```
12>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\test-server\test-server-libuv.c(243): warning C4013: 'setlogmask' undefined; assuming extern returning int
12>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\test-server\test-server-libuv.c(243): warning C4013: 'LOG_UPTO' undefined; assuming extern returning int
12>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\test-server\test-server-libuv.c(243): error C2065: 'LOG_DEBUG' : undeclared identifier
12>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\test-server\test-server-libuv.c(244): warning C4013: 'openlog' undefined; assuming extern returning int
12>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\test-server\test-server-libuv.c(244): error C2065: 'syslog_options' : undeclared identifier
12>d:\dev\cpp\game_servers\libwebsockets\libwebsockets\test-server\test-server-libuv.c(244): error C2065: 'LOG_DAEMON' : undeclared identifier
```

**Comment by meiry** [comment]
i did few fixes : 
test-server-libuv.c
added #ifndef _WIN32  line 243
```
#ifndef _WIN32
	/* we will only try to log things according to our debug_level */
	setlogmask(LOG_UPTO (LOG_DEBUG));
	openlog("lwsts", syslog_options, LOG_DAEMON);
#endif
```


file libuv.c : line 217 should be :  
```
wsi->w_read.uv_watcher.events

```

line 42 : should be :  
```
eventfd.fd = watcher->socket;
```

**Comment by lws-team** [comment]
Thanks, I pushed them on master in a patch under your name.

That leaves it workable on windows, or still broken?

**Comment by meiry** [comment]
Thanks , please see the updated answer , there is need to make more changes

**Comment by lws-team** [comment]
Sorry which updated answer... it's stuff around line 195 or something else?

**Comment by meiry** [comment]
just added with the libs

**Comment by meiry** [comment]
New problems on run time while running on debug 
![cmd](https://cloud.githubusercontent.com/assets/1107316/14201544/5097babe-f7fb-11e5-928b-6068d949623b.png)

The exception stack starting from libuv.c line 144 
```
while (vh) {
		if (vh->lserv_wsi) {
			vh->lserv_wsi->w_read.context = context;
			uv_poll_init(pt->io_loop_uv,
				     &vh->lserv_wsi->w_read.uv_watcher,
				     vh->lserv_wsi->sock);  // <<<<< HERE!!!
			uv_poll_start(&vh->lserv_wsi->w_read.uv_watcher,
				      UV_READABLE, lws_io_cb);
		}
		vh = vh->vhost_next;
	}
```

![stack](https://cloud.githubusercontent.com/assets/1107316/14201597/9e563906-f7fb-11e5-99af-14d951acd489.png)

**Comment by lws-team** [comment]
That doesn't occur on Linux / lws / libwebsockets-test-server-libuv...

**Comment by lws-team** [comment]
It looks like it wants us to use

```
int uv_poll_init_socket(uv_loop_t* loop, uv_poll_t* handle,
    uv_os_sock_t socket) {
```

that also exists in the unix plat libuv implementation.  I'll look at moving to that.

**Comment by lws-team** [comment]
Please try

https://github.com/warmcat/libwebsockets/commit/0d0124a36c8085f3221ad0382b2d87e5b87653c4
(it's pushed on master)

It looks like maybe init is failing silently, it calls through to the right api already and should set the UV_POLL flag it's complaining about there.  So this increases the error checking and reporting.

**Comment by meiry** [comment]
i toke the master again fresh clone 
it still have the same error on run time :  
```
while (vh) {
		if (vh->lserv_wsi) {
			vh->lserv_wsi->w_read.context = context;
			n = uv_poll_init(pt->io_loop_uv,
				     &vh->lserv_wsi->w_read.uv_watcher,
				     vh->lserv_wsi->sock);  //<< ==== START HERE!!!!!
			if (n) {
				lwsl_err("uv_poll_init failed %d, sockfd=%p\n",
					n, (void *)(long)vh->lserv_wsi->sock);

				return -1;
			}
```

**Comment by lws-team** [comment]
According to your backtrace, we're blowing up in here

```
INLINE static HANDLE uv__get_osfhandle(int fd)
{
  /* _get_osfhandle() raises an assert in debug builds if the FD is invalid. */
  /* But  it also correctly checks the FD and returns INVALID_HANDLE_VALUE */
  /* for invalid FDs in release builds (or if you let the assert continue).  */
  /* So this wrapper function disables asserts when calling _get_osfhandle. */

  HANDLE handle;
  UV_BEGIN_DISABLE_CRT_ASSERT();
  handle = (HANDLE) _get_osfhandle(fd);   <<<====
  UV_END_DISABLE_CRT_ASSERT();
  return handle;
}
```

_get_osfhandle() is some windows thing

https://msdn.microsoft.com/en-us/library/aa297958(v=vs.60).aspx

If it's blowing a segfault or so, maybe the fd we pass it is junk... can you dump the sock handle before the call to uv_poll_init() in libuv.c?

                `lwsl_err("    sock handle=%p\n", (void *)(long)vh->lserv_wsi->sock);`

and check the handle / pointer is sane?

**Comment by meiry** [comment]
i dump it here : 
```
lwsl_err("    sock handle=%p\n", (void *)(long)vh->lserv_wsi->sock);
			n = uv_poll_init(pt->io_loop_uv,
				     &vh->lserv_wsi->w_read.uv_watcher,
				     vh->lserv_wsi->sock);
```
the output is : 
[2016/03/02 08:13:15:6050] ERR:     sock handle=0000008C

**Comment by alexhultman** [comment]
You need to use uv_poll_init_socket instead of uv_poll_init to also support Windows. And pass a SOCKET type instead of int when on Windows. uv_poll_init_socket is the same as uv_poll_init on Unix.

http://docs.libuv.org/en/v1.x/poll.html

**Comment by meiry** [comment]
@alexhultman 
Its working thanks i made it like this :  
```
#if defined(WIN32) || defined(_WIN32)
			n = uv_poll_init_socket(pt->io_loop_uv,
				     &vh->lserv_wsi->w_read.uv_watcher,
				     vh->lserv_wsi->sock);
#else
			n = uv_poll_init(pt->io_loop_uv,
				&vh->lserv_wsi->w_read.uv_watcher,
				vh->lserv_wsi->sock);
#endif
```

**Comment by alexhultman** [comment]
You don't need to ifdef it. Use uv_poll_init_socket on all platforms.

**Comment by lws-team** [comment]
Thanks.... I pushed it on both branches.  Nice news we're working on Windows with libuv (because the default loop there is really bad).

**Comment by meiry** [comment]
New problem on windows , lts try to fix this also 
i try now to build with OpenSSL support using cmake GUI 
Using :openssl-1.0.1e-win32-bin
but im getting errors when trying to generate the project files 
![ssl](https://cloud.githubusercontent.com/assets/1107316/14274842/7269fdc2-fb1c-11e5-8843-a5298df5948b.png)

**Comment by meiry** [comment]
@lws-team  
i git clone the project again and i found that there are still missing things when compiling test-server-libuv


1. The generate project dosn't include the libuv.lib in the VC Linker->input->Additional dependencies
not only this there are also another system libs that are missing they are : 
iphlpapi.lib
psapi.lib
userenv.lib

see the run-test project in libuv  so here are the pictures 
Before :
![befor_libs](https://cloud.githubusercontent.com/assets/1107316/14275163/61a5c780-fb1e-11e5-8173-91dd6b877f95.png)

After adding it manually :
![after_libs](https://cloud.githubusercontent.com/assets/1107316/14275167/682abc82-fb1e-11e5-9442-f0a98e4ff072.png)

2. Another important step is compile libuv as Multi-thread-dll  /MTd
as libwebsocket and libuv should be the same 
if not it will not compile  compile

**Comment by lws-team** [comment]
Do you have a patch on CMakelists.txt to solve these?

**Comment by meiry** [comment]
unfortunately no i did those fixes manually , i need to dig into the CMakelists.txt
i will try to do it latter , 
About the section 2 . i guess it will be helpful to point somewhere in the doc.

**Comment by lws-team** [comment]
Thanks.... windows is very difficult to work on because I can't test anything.

I'll add a section in README.build later.

**Comment by meiry** [comment]
@lws-team 
Im sorry for multiple massages but i hope it will help others not only me . as i need to develop it on windows . 
i have problem with the test servers , after  reading the minimal help in https://libwebsockets.org/index.html

i tryed to test the test-server example i run it from VC with command argument : 
```
-r  g:/dev/cpp/servers/libuv_and_libsocket/libwebsockets/libwebsockets/build/bin/Debug 
```
while the server do start right with no errors , when i try to browse : http://127.0.0.1:7681/
im getting exception : 
![time_exp](https://cloud.githubusercontent.com/assets/1107316/14278438/67b4d398-fb30-11e5-9ded-a429a3078ebf.png)


![exc_src](https://cloud.githubusercontent.com/assets/1107316/14278493/b95439e6-fb30-11e5-8e8a-1229055b5b5c.png)


ptm has all the data in the struct , according to : https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx
it suppose to work 

![ptm](https://cloud.githubusercontent.com/assets/1107316/14278613/437cb4fe-fb31-11e5-9cdc-f4c29b2ecdbe.png)

**Comment by meiry** [comment]
Ok i see that the The formatting codes in windows are different

**Comment by meiry** [comment]
Yet another bug 
after fixing the data print in windows , 
in file : test-server-status.c
in function :  callback_lws_status(struct lws *wsi, enum lws_callback_reasons reason,
		    void *user, void *in, size_t len)
in line 118 the pss->list = list;   
The list is empty 
now Further in the code : 
in function : update_status(struct lws *wsi, struct per_session_data__lws_status *pss)
line : 35 
```
struct per_session_data__lws_status **pp = &list;

the **pp is pointing to structure which the list member is not valid
the first iteration in the while loop in line 49 will run successfully
but then in the end of this loop it will pass garbage data and this loop while throw exception 
```
	/* render the list */
	while (*pp) {
		t = (*pp)->tv_established.tv_sec;
#ifdef WIN32
		ptm = localtime(&t);
		if (!ptm)
#else
		ptm = &tm;
		if (!localtime_r(&t, &tm))
#endif
			strcpy(date, "unknown");
		else
			strftime(date, sizeof(date), "%Y %H:%M %Z", ptm);
			//strftime(date, sizeof(date), "%F %H:%M %Z", ptm);
		if ((p - start) > (sizeof(cache) - 512))
			break;
		if (subsequent)
			*p++ = ',';
		subsequent = 1;
		p += snprintf(p, sizeof(cache) - (p - start) - 1,
				"{\"peer\":\"%s\",\"time\":\"%s\","
				"\"ua\":\"%s\"}",
			     (*pp)->ip, date, (*pp)->user_agent);
		pp = &((*pp)->list);   <<<=== HERE IT WILL PASS GARBAGE DATA 
	}
```

**Comment by lws-team** [comment]
I pushed the strftime thing and the README.build.md notes.

But I don't really understand the last crash bug.  I am running the test server fulltime for many weeks and he hasn't crashed.  I'll look closer at it in case I missed the point.

**Comment by meiry** [comment]
@lws-team 
Thanks for the fast response very Appreciate it as i try to push using your lib at work. 
Did you run it on windows ? 

Also i as im trying to learn the lib i notice something very strange. 
i created new simple c++ server without libuv and when i try to link it against libwebsocket (static) 
it still needs the libuv library ..  why is that ? 
I thought libwebsocket is in depended 
i do use the libwebsocket which i used to try to test the libuv

**Comment by lws-team** [comment]
No we rely on contributors to test on windows.  Users who are interested in windows come and go.  New features like libuv support wait for someone who cares about Windows to test them.

I guess the library you link against is maybe not what you think it is (ie, it is the one built with libuv).

CMake caches option selections and it can get confusing which options are still active.  You can try delete the output directory ("build" or so) and use default cmake options from scratch.

**Comment by meiry** [comment]
I see thanks , i will create 2 versions in the mean time one for libuv 
and one without . 
also i will keep testing the libuv side in windows . 
by the way what client should i use and how to test the server-libuv-test ?

**Comment by JoakimSoderberg** [comment]
As @lws-team says if you're getting weird stuff like this with options. Make sure you clean your build dir so nothing cached is left.

The CMake stuff that chooses between different SSL libraries is kind of a mess since last I looked at it. I see many potential parts where it can get confused if you turn stuff on and off.

The instructions note that you should preferably use the default location for the OpenSSL binaries. Which it seems you haven't... And since windows has not proper paths to place libs, the cmake find script needs some hints on where you have put it.

But yea, I woudl still recommend the default `C:\OpenSSL` location if you just want it to be as painless as possible

**Comment by lws-team** [comment]
You can use any browser as the client.  For lws as client, there is a libwebsockets-test-client that shows how to do.  He spams circles on the mirror test shared canvas.

**Comment by meiry** [comment]
@JoakimSoderberg 
Ok Thanks for the response.

**Comment by meiry** [comment]
@lws-team 
Basic question 
as i work with the lib building simple websocket servers it is all clear . ( on the basic level ) 
but when i go back and check the test-server-libuv.c code i find it super complex to reverse engineer it 
i see that the glow layer libuv.c is tightly coupled and it is very hard for the Newbie user to decipher whats going on . 
is there any document or something to explain what you did there ? 
Thanks

**Comment by lws-team** [comment]
Implementing a libuv server is just cut and paste a handful of lines from the libuv test server... I did it yesterday myself.  That's not 'super complex' or 'reverse engineering'.

What are you actually trying to do?

**Comment by meiry** [comment]
Yes you are right as i continue with the learning curve i see the modularety of the code . 
At first it does looks abit complex .
what im doing is Async server with websocket interface , what i have today is java netty 
i want native none JVM replacement

**Comment by lws-team** [comment]
The main thing is libuv.c is private library internals, although you had to go look in there to get it working on windows, actually all that is hidden just to use the library.

lws is designed to provide standalone http[s] and ws[s] in a very lightweight way with no other framework around, if you're okay writing your app logic in C it should do what you want well.

**Comment by meiry** [comment]
Continuing with the windows port .
Now i git cloned the libwebsocket without the libuv dependencies.
Compiling in windows i got those compilation errors  . 
```
libwebsockets_pure\libwebsockets\lib\libwebsockets.c(1093): warning C4013: 'snprintf' undefined; assuming extern returning int
``` 

I have to set a fix in 3 files : 
this is the fix : 
```
#ifdef WIN32
#define snprintf _snprintf
#endif
```

libwebsockets.c
server.c
test-server-status.c

**Comment by lws-team** [comment]
Thanks... I moved it to libwebsockets.h so it's in one place and pushed on master + v1.7-stable.
