### ISSUE TITLE
assert in pollfd.c

### ISSUE THREAD

**Issue by ondraco** [warmcat/libwebsockets#437]
Hello,

I have just switched form LWS 1.6 to LWS 1.7.1 (no ssl, win32) and now got following assert on `lws_client_connect` (pollfd.c line: 38):

`assert(wsi->position_in_fds_table >= 0 &&
	       wsi->position_in_fds_table < pt->fds_count);`

(position_in_fds_table = 0, fds_count = 0)

 being fired on: 

`_lws_change_pollfd(lws * wsi, int _and=0, int _or=9, lws_pollargs * pa)  Line 39`
`lws_header_table_attach(lws * wsi)  Line 150`
`lws_client_connect_via_info(lws_client_connect_info * i)  Line 407`
`lws_client_connect(lws_context * context const char * address, int port, int ssl_connection=0, const char * path, const char * host, const char * origin, const char * protocol, int ietf_version_or_minus_one=-1)  Line 568`

Am I doing something wrong or is it a bug? 

Thank you for LWS and your help!

**Comment by lws-team** [comment]
Does this help?

https://github.com/warmcat/libwebsockets/commit/5cd8bef3467462dd9cd80257ecbc31583ad1710f

**Comment by ondraco** [comment]
It seems that this change breaks it.

One version before it is possible to connect to both web server and web socket server (the assert is fired) and also it seems that some events are not later fired (for example LWS_CALLBACK_CLOSED)

After the patch it is not even possible to connect. Server is started, netstat says that port is opened but no callback is ever fired and no logger output is shown.

**Comment by lws-team** [comment]
Sorry I realized that it was already correct before that patch... unix has an extra pipe in the poll() so he should start from 1.  But windows doesn't.

I removed that patch and pushed a different fix someone else noticed in the meanwhile, please fetch again and retry.

**Comment by ondraco** [comment]
The assert is gone and the connection works but there is still one problem.
After the server closes the connection no callback is called. This is the output of the log:

```
Session Socket 02FDFE68 (fd=708) dead
Close and handled
lws_close_free_wsi: real just_kill_connection: 02FDFE68
remove_wsi_socket_from_fds: wsi=02FDFE68, sock=708, fds pos=0, end guy pos=1, endfd=0
not calling back closed mode=4 state=0
```

 `wsi->state_pre_close = 0` 
`wsi->mode = 4 (LWSCM_WS_CLIENT)`

This also seems to be bug right (worked in 1.6)? 

Thank you for your help!

**Comment by lws-team** [comment]
Glad the first problem is solved.

I will look at the second problem...

**Comment by lws-team** [comment]
Well... please try the patch I just pushed (on master and v1.7-stable)... it should at least make LWS_CALLBACK_CLOSED appear.

**Comment by ondraco** [comment]
Hello, this have not fixed the issue. This is a WS connection between two processes both running LWS.

The connection is upgraded and `wsi->state = LWSS_DEAD_SOCKET` when lines 370+ in libwebsockets.c are executed.

**Comment by lws-team** [comment]
Yes my patch did not check the incoming state but current state :-/  However I just got sent the correct fix which is applied now in place of mine.

**Comment by lws-team** [comment]
There's a 1.7.2 release now with these fixes in.

**Comment by ondraco** [comment]
This problem seems to be fixed. Thanks!
