### ISSUE TITLE
Regression in libwebsockets 2.1.0 - unable to connect to mosquitto via websocket

### ISSUE THREAD

**Issue by brandond** [warmcat/libwebsockets#774]
Per https://github.com/eclipse/mosquitto/issues/336#issuecomment-274247609:

>I've been testing this and I think it is a regression in libwebsockets 2.1. Nothing I've been able to do will make things work on libwebsockets 2.1. Using the latest code from lws git is fine.
>
>I think we need to wait until libwebsockets 2.1.1 is released.

Have not got around to doing a bisect to figure out which commit fixed it, but it appears that the 2.1.0 release does not work with mosquitto, period.

**Comment by lws-team** [comment]
Did you try v2.1-stable?  This has many backported patches from master.  It's this that would become the point release.

**Comment by lws-team** [comment]
I released  v2.1-stable as v2.1.1 and that seems to solve it

https://libwebsockets.org/pipermail/libwebsockets/2017-February/003160.html

**Comment by flexiti** [comment]
Sorry for the simple question but I'm rather a man of windows :)
`sudo apt-get install libwebsockets` 
install v2.1-stable, How to install v2.1.1 instead to check if it helps ?
(After the upgrade ubuntu mosquitto via WebSockets not  working )

**Comment by lws-team** [comment]
No v2.1-stable is v2.1 + latest backport patches.  At the moment v2.1-stable and v2.1.1 are almost identical and either should fix the problem.

What is packaged will be something earlier like v2.1.0.

Ideally you can recook the .deb, or get a fixed .deb from a later ubuntu version.  If not, you can install lws from git

Using lws from git you want something like

```
 $ git clone https://github.com/warmcat/libwebsockets
 $ cd libwebsockets
 $ git checkout v2.1.1
 $ mkdir build
 $ cd build
 $ cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr
 $ make && sudo make install
 $ sudo ldconfig
```

But you will need to check if this places the library over the packaged one... this is just general guidence...

**Comment by flexiti** [comment]
Thanks :)

**Comment by flexiti** [comment]
lws from git:
Still not working, effect the same.
I do not know if I'll copy compiling results in a good place (I think so).
How can I check what libwebsockets is seen by the system, how to check the version? (on Ubuntu 14.04)

**Comment by lws-team** [comment]
If what you are running that uses lws is called 'xxx', then look at

```
 $ ldd `which xxx`
```

It will list all the dynamic libs wanted by xxx, and show where it's getting them from.

**Comment by flexiti** [comment]
mosquitto
but the problem is:
if protocol websockets in config mosquitto file  is active 
mosquitto not start

Here is log when websockets is commented
![libs](https://cloud.githubusercontent.com/assets/11538048/23452793/ff1ee460-fe65-11e6-94e4-930ab4ff840d.JPG)

I will try check , if I can find something in the log mosquitto

**Comment by lws-team** [comment]
I assume it uses libdl to load libwebsockets.so dynamically then... since the newer lws is supposed to solve it the only thing needed is supposedly replace packaged libwebsockets.so* with the one you built.

You should be able to do like `dpkg -L libwebsockets8` to see where the package puts things.  (I am not 100% sure what the package is called in your Ubuntu).

**Comment by flexiti** [comment]
all looks ok, but no progress.

In mosquitto log only : Websockets support not available
(if I copied it wrong, at least the old should be.. hmhm)

**Comment by lws-team** [comment]
What does `dpkg -L libwebsockets8 | grep so` say?

You need to remove those and sudo cp the git-built .so pieces in there instead.

**Comment by flexiti** [comment]
![3](https://cloud.githubusercontent.com/assets/11538048/23456738/ff587f04-fe74-11e6-9975-4a47d2e93ce6.JPG)
already copied  (yours  libwebsockets.so.9 to /usr/lib/i386-linux-gnu/libwebsockets.so.8)

**Comment by flexiti** [comment]
https://github.com/eclipse/mosquitto/issues/336

**Comment by flexiti** [comment]
I am back on mosquitto 1.4.08 (libwebsockets 2.0.2) and it work
(all on UBuntu 14.04)

No I will try libwebsockets 2.1.1 and see if it work
