### ISSUE TITLE
Server context with simultaneous_ssl_restriction set to zero prevents SSL connections

### ISSUE THREAD

**Issue by skyhisi** [warmcat/libwebsockets#867]
Creating a server context with `simultaneous_ssl_restriction` set to 0, causes the server to not accept any connections, instead of an unlimited number as documented.

This appears to have been added in commit 00ae9097, which is the point at which my test server breaks. For my test server, setting the value to 10 is fine, but it would be useful to set it to unlimited.

**Comment by lws-team** [comment]
"whoops" :-/ ... I pushed a fix, the change only exists on master.

**Comment by skyhisi** [comment]
Sorry, but the patch didn't fix it, I think a couple of the conditions are inverted.
In ssl.c lines 480 and 528, I think the condition needs to be:
`if (!wsi->context->simultaneous_ssl_restriction || ...`

**Comment by lws-team** [comment]
Maybe I am especially distracted today, but I don't see it.

If there is no restriction, it doesn't have to take care about counting ssl connections, comparing with the limit, and gating or ungating them.

I also confirmed this worked in ssl with the test server before pushing it.

**Comment by skyhisi** [comment]
Ok, I'll re-test my code, I might have changed something unrelated which has broken it.

**Comment by skyhisi** [comment]
It was a build error with my code, I hadn't actually linked in the new version, the patch is fine.
Thanks,
Silas
